### ISSUE TITLE
Tool Profile for CWRC project page with accompanying blog post

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#1]
- Establishing a presence on the CWRC site will help generate interest in the tool and connect us with future users
- Tool profile to be adapted from DHSI 2015 poster presentation
- Include hyperlinks to beta tool and documentation to-date
- Resulting description could be incorporated into the Quick Guide
- Add “contact us” link for interested scholars/future users to contact us for more info (feedback could be incorporated into user testing)

**Comment by cmiya** [comment]
As Jana pointed out, we will have to hold off on the hyperlink to the beta tool until things like snippet length (which is a copyright issue) are sorted out.

**Comment by cmiya** [comment]
As per Mihaela's suggestion - in the future, perhaps we can create a separate huvis email, but for now we can list the cwrc@ualberta.ca email as a way for scholars/researchers who are interested in the tool to get in touch, ask questions, etc.

**Comment by ilovan** [comment]
@cmiya , have you been able to use the credentials I created for you to log in to the CWRC WordPress site? Please confirm. the account was created on Tuesday and you should have received an email notification.

**Comment by cmiya** [comment]
Yep, I'm able to log on. Thanks Mihaela!
