### ISSUE TITLE
toggling the selectedness of things via the set picker does not always update the class picker appropriately

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#101]
Sometimes the class selector is completely unresponsive.

**Comment by cmiya** [comment]
Related to #35?

**Comment by smurp** [comment]
An unresponsive class selector has meant that it was actually bogged down and performing a command already.  So just as @cmiya has suggested, related to #35.  In other words, perhaps the unresponsiveness has been solved?  I think I used to see set-picker and class-picker having slightly different impacts, but I haven't seen that in quite a while.

**Comment by smurp** [comment]
I would say this is likely fixed, so closing it now or remaining alert to this one for a while and reviewing it in a couple of months would be in order.

**Comment by antimony27** [comment]
I've played with the class selector quite a bit and it seems to be working well. Closing, as it was likely part of #35 as noted above.
