### ISSUE TITLE
snippets and labels

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#117]
This follows on from https://github.com/cwrc/HuViz/issues/116 about snippets but has to do with how HuViz handles them in the interface.

Right now with the data structured as per the sample data in #116, we can access the snippets by clicking on the edges for prov:derived from. However, because the nodes contents are literals and there are no separate labels, the very lengthy snippet appears as the node label as well. When we add a label, that takes care of that problem, but the ability to access the content through the edge disappears.

Here's an example of how the data provided below looks, with the snippet with the label first (raw data provided below but line breaks lost to harder to read):
![image](https://user-images.githubusercontent.com/545952/28756120-6338fd04-7536-11e7-97fa-63d25abdabd9.png)

![image](https://user-images.githubusercontent.com/545952/28756110-2bbd715c-7536-11e7-8b34-90a3a7420f2b.png)

Sample data with label (can't access the literal/content of the snippet in HuViz):

`<http://www.cwrc.ca/cwrcdata/annaleanowens1>
    rdfs:label "Orlando Entry Excerpt" ;
    nif:isString """Although AL herself, in attempting to adopt an unequivocally English identity, implicitly claimed that she was white, evidence suggests that while
her father was probably Welsh (he had lived in Middlesex) and presumably white, her mother was quite possibly Eurasian. If this is the case then
AL suppressed her mixed-race origins. Anna was multi-lingual and from childhood could speak Hindustani, English and Guzerati (also called 
Gujarati), which was taught to her by her mother. She also became fluent in Sanskrit,French ,Thai , Malay,  Arabic, Persian, Latin and Pali. 
She knew some Russian from her travels. AL was Presbyterian but also studied Hinduism and Buddhism. She believed that she was too good a Christian 
not to be something of a Buddhist, and too good a Buddhist not to be something of a Christian."@en ;
    a nif:Context, nif:Sentence ;
    prov:createdBy cwrc:originalOrlandoAuthor .
`

Sample data without label (snippet shows up when one clicks on the prov:derivedFromedge):
`
<http://www.cwrc.ca/cwrcdata/annaleanowens2>
    rdfs:label """AL often visited the Reclining Buddha at the temple Wat Po in Bangkok. Her Thai teacher gave her frequent instruction on Buddha's teachings. Later in
Siamese Harem Life, Anna recalled that she had learned that the prophet's object was not only a religious but a social revolution. A good deal of what
was venerated as religion he found to be merely social usage, for which a Divine sanction was feigned. [Buddha], without hesitation, rejected all of
this . . . . His greatest blow to the old religion, however, was in his explicit repudiation of caste. He offered his religion to all men alike . . . . 
Buddha boldly expounded to the people that, according to their own books, all men were equal.""" ;
    a nif:Context, nif:Sentence ;
    prov:createdBy cwrc:originalOrlandoAuthor .`

**Comment by antimony27** [comment]
Update: the newest version of the Woolf data still shows the snippets as nodes, some of which are quite lengthy. Given that we've made many changes to the data since 2017, what is it that we want to see instead of this:

![image](https://user-images.githubusercontent.com/11494469/48072379-5ca7f080-e1aa-11e8-903e-da0d9dfc3ae7.png)

Dataset: WoolfsOrlando ontology: CWRC in Beta

@SusanBrown @smurp @cmiya

**Comment by antimony27** [comment]
@SusanBrown since snippets no longer work like this, I think we can close?
