### ISSUE TITLE
Load custom set from Orlando

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#12]
- Make available the ability to create datasets by administrators of the tool

NOTES:
Also if it's possible: implement a file upload functionality. OrlandoScrape tool can be run locally if GitHub is run to extract datasets. Bring your own XML. This process needs to be documented. Chelsea needs to know how to do it. How tricky to set up a web interface to the extraction facility. Upload datasets through the web...? work with triplestore instead if it would be a timesaver

**Comment by smurp** [comment]
It would take about 8 to 16 hours to do a nice job of developing a web interface for building and managing data extractions.  The initial implementation would have form fields where one would type in the comma delimited lists of authors and/or predicates which orlandoScrape needs to do its work.  Time permitting, it could be made more user friendly with the SELECT fields for picking the authors and the predicate from the xpath rule set.  

Choices will need to be made concerning the prioritization of features like:
* ruleset editing through the web interface and/or
* extract uploading

There are dependencies between extracts and the XML files they come from too, so feature creep could make this thing fairly involved.  Perhaps a meeting to mock it up and nail the spec would be appropriate.

**Comment by smurp** [comment]
When we implement a QuadStore on the server-side then the goals served by this task would be met.  So, given that we're recognizing that other issues (such as #48, #37, #49, #67) are obviated or significantly altered by #68 maybe prioritizing it before this task is appropriate.

**Comment by cmiya** [comment]
What are our thoughts on this task at this point? Does it need to be closed, postponed...?

**Comment by SusanBrown** [comment]
I think we should defer this and move ahead instead on the general functionality for loading from a SPARQL end point. We should ensure that the functionality we wanted for loading from Orlando would be covered by this.
