### ISSUE TITLE
Increase default size of fisheye radius to 300

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#127]

**Comment by SusanBrown** [comment]
@smurp I know you said it was deployed but it is still what it was.

**Comment by smurp** [comment]
Haha!  There were two places it needed changing -- one place which provides an initial value (which is actually respected by the renderer) and another which provides an initial value for the Settings slider.  I had changed the first but not the second -- with the effect that it did affect the initial rendering -- but when one went to adjust it then it would reset to 100 and appear to not have been altered. 

There is a new issue which addresses this duplication: https://github.com/smurp/huviz/issues/94

**Comment by smurp** [comment]
https://github.com/smurp/huviz/commit/b9841094e5e7c937eda6ff36bce14268854cec91
