### ISSUE TITLE
Load own data set

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#13]

**Comment by ilovan** [comment]
related to #12

**Comment by smurp** [comment]
I've got some code that's nearly done on this one.  It (almost!) let's users load a dataset from their own drive into the HuViz tool running in their browser, without involving the server.  I got started on this line of investigation (it is a little weird to load data from a local source into a single page app like HuViz without it passing through the server) and was nearly done but for a smallish bug.  Shouldn't be more than a couple hours to get going.

**Comment by cmiya** [comment]
That's great! It's an exciting future development. It seems like there is a lot of potential for synchronization between HuViz and CWRC-writer. In the future, it would be great if users could annotate and export their data in CWRC-writer and import it into HuViz for analysis.
