### ISSUE TITLE
Simplifying the Way Predicates are Expressed in the Graph/Commands Tab:

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#146]
This is from a 2015 email by @cmiya Chelsea, can you think through whether this issue is still relevant. I think @SusanBrown should likely weigh in as well.

Issue: Is there a way to simplify the Edge Labels?
For example, in the graph we know that subject node “Margaret Atwood” is Connected to object node “Toronto” because this information is already expressed visually: through the connective line and the fact that Atwood is the central hub node. Couldn’t the pop-up label for the edge simply read “Work”?
Likewise, the Edges of Selected Nodes Box is crowded with labels/text, which makes the information difficult to absorb. The drawers typically read something like this:
HasMaterialConditions (0/0)
HasMaterialConditionsConnectionToDate (0/1)
HasMaterialConditionsConnectionToGeog (0/0)
HasMaterialConditionsConnectionToRegion (0/1)
HasMaterialConditionsConnectionToOrganization (0/2)
Is it necessary to include the full statement? Can this be simplified?
For example, why not have the main folder read MaterialConditionsConnectionTo: and the subfolders read Date, Geog, Region, Organization?

**Comment by SusanBrown** [comment]
These are terms from the old quite mechanically generated ontology. I don’t think they apply (as much) to the current one.


On Mar 5, 2018, at 10:22 AM, antimony27 <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #146<https://github.com/cwrc/HuViz/issues/146> to @SusanBrown<https://github.com/susanbrown>.
