### ISSUE TITLE
Reload button

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#149]
* [x] Put on right side of the box at top of the Command Box where datasets are listed.
* [ ] Implement an "are you sure" dialog so the user has to click again before they lose their work.
* [ ] fix the bug where the words Dataset and Ontology appear where the names of the picked ones are expected

**Comment by cmiya** [comment]
Any updates on reimplementing the reload function? I *think* it was removed before due to bugginess, but it's possible that the underlying issues have already been fixed. Thoughts...? The reason I ask is because if it's a relatively simple fix, maybe it could be part of the fall milestone tasks?

**Comment by smurp** [comment]
closed by https://github.com/smurp/huviz/commit/e81ae0f01c04c51586b40aae488fc4f61b219200

**Comment by smurp** [comment]
see  #8

**Comment by smurp** [comment]
The *Rewind* button on the `History` tab undoes everything in the graph, as distinct from the *Reload* button on the `Commands` tab which actually reloads the data and the page.  Either way, this feature is now complete.
