### ISSUE TITLE
Some regex producing values rather than labels

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#15]
- There is some wonky stuff with the triples. For example, on Maria Abdy, there is a link that says: Abdy, Maria, Connection with Settlement: Interested in science, she was frustrated how...etc.
- Shawn says: Another current challenge is that there are a few of the regexes which are producing "values" which cause some very long labels. I haven't had a chance to isolate the cause of those yet.
- Still showing labels in the set picker and history; Some long labels still appear in graph; this may be a problem on our end with data

**Comment by ilovan** [comment]
@smurp , should we wait trying to fix this until the new ontology has been integrated?

**Comment by cmiya** [comment]
Can we close this issue?

**Comment by SusanBrown** [comment]
Relates to soon-to-be-obsolete dataset so I think so.



On Sep 8, 2017, at 6:46 PM, cmiya <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we close this issue?
