### ISSUE TITLE
Credit page update

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#151]
@smurp Can you please point me to the text of the credit page so I can add new sponsors, update rolls, etc?

**Comment by smurp** [comment]
https://github.com/smurp/huviz/blob/alpha/docs/credits.md

The credits are in this markdown file.  You should be able to edit it directly via the GitHub UX using the "edit" button (the pencil icon).

**Comment by SusanBrown** [comment]
I've updated them. I also replaced (or so I think) the CWRC logo with a smaller one, but it is not showing up as smaller in github, maybe because it pushed to alpha? However, sizing is fine in the HuViz interface, alpha version, and changes are reflected, so this is good for now. @smurp pls push to these to beta and prod as well.

**Comment by SusanBrown** [comment]
I was jumping the gun slightly in asking for the push to the other sites, @smurp 

@antimony27 if you see any opportunity for further updates, and could add sshrc and canarie logos (although I think there may be some magic happening on the interface end re: their layout that would need to be considered, in which case @smurp should tell us to hold off), that would be great.

**Comment by smurp** [comment]
I don't know of anything special to be done about the logos you mention @SusanBrown so I think we'd be good to go with what @antimony27 might do.

I've already pushed a recent alpha to beta (but goofed and didn't push beta to prod first).  Fixable, but with a mildly creased forehead :-)   Maybe give me the word when (or at what breakpoint) to do those pushes?

**Comment by SusanBrown** [comment]
ASAP would be best, I think, and then pls give us the heads up to test. @smurp

**Comment by smurp** [comment]
Beta is pushed as of a couple of hours ago

**Comment by smurp** [comment]
@antimony27 Are your changes complete and visible on alpha?  If so feel free to mark this one closed

**Comment by antimony27** [comment]
The SSHRC and the Canarie logos still need some work. @SusanBrown and I had a hard time getting them to look good. @smurp do you know if there is a certain file format that might improve this?

**Comment by smurp** [comment]
Hey @wolfmaul could you tune up the stylesheet so the SSHRC logo isn't so mangled.  Maybe tuning the Markdown in src/credits.md will be required too, for prettiness.

**Comment by antimony27** [comment]
The logos look great and the text is all streamlined. Thanks @wolfmaul ! Closing.
