### ISSUE TITLE
Remove datasets from picklist

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#160]
The following datasets aren't accessible any longer in the locations the dropdown expects: https://raw.githubusercontent.com/cwrc/testData/master/demoData/CanAuthors.ttl
https://raw.githubusercontent.com/cwrc/ontology/master/demoData/CWRCTestData.ttl
https://github.com/cwrc/testData/blob/master/demoData/HuVizMarylandSTSData.ttl
and Grace and Charlotte

**Comment by smurp** [comment]
closed by https://github.com/smurp/huviz/commit/54682d6b746fe86a8f1827ec1bd51ebd60b0dc30
