### ISSUE TITLE
Make a verb `open` to open a node's URI in a tab

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#164]

**Comment by smurp** [comment]
Imagine a verb which opens as a link in a new tab the URI of the node. 

Given that these nodes in the graph do not actually have any A-tag associated with them it seems likely that we will have to create an A-tag for the URI in question and then send it the click.  This A-tag should probably be invisible.  We should be able to do with just one of them I think, even though we are likely to need to deal with the situation where OPEN is run on more than one node, ie with a command like: `Open Person.`.  Under such circumstances we would presumably loop through the nodes, updating the A-tag to be each one in turn and sending click to it.  

https://stackoverflow.com/questions/902713/how-do-i-programmatically-click-a-link-with-javascript

@SusanBrown has indicated that her preference would be that the pages get opened in just a single external tab, but I would suggest that if multiple items were being opened that they ought to use `target="_blank"` so each opens in its own tab.


https://html.com/attributes/a-target/

**Comment by smurp** [comment]
The initial inspiration for this `open` verb is dealing with nodes which are the object of `owl:sameAs` relations but all nodes have an URI, so should be subject to this verb.  To be able to experience the opening of `sameAs` URIs we will have to complete issue #163

**Comment by SusanBrown** [comment]
There is the potential to open hundreds of new tabs in a browser if Open will be actionable on whole classes. I think we should either restrict this functionality to working with single clicks on particular nodes in the graph (my preference) or we will need to put in place a warning that says something like "You are about to open 265 tabs. Do you want to proceed?"

**Comment by smurp** [comment]
Hey @wolfmaul heads up concerning which nodes you try to `open` during development.  The `writers` in the Orlando data are good nodes to focus on because they have lovely full URIs over at Cambridge, but many (most?) other nodes aren't even resolvable because they are so-called `blank nodes`, meaning that they are not resources out in the wide world but just have URIs like `_:AB` which only have meaning within the context of the dataset.  The CWRC data probably has more real external resources, but I don't know the data as well.

**Comment by wolfmaul** [comment]
Here are a couple ideas about the UX....

One way would be to create a tool-set (buttons) that change the selection mode of a mouse click. Normal mode would have current click functionality. Selecting a different mode would change clicking on a node to open the node URI in a new tab/window. Other modes can be easily added later: e.g. a 'peek' mode where clicking a node reveals all data on that node. This tool functionality is somewhat like Adobe illustrator (or other drawing programs) --  a pick tool (normal mode), drawing tool modes, text mode, etc. In each case the curser/click action changes (everywhere) with the current tool selection. The interface itself could be a new row of buttons in the command tab above the "Current Command" box. The up-side of the interface is that the new functionality is very visible - i.e. tools are not hidden. A couple downsides are that it adds more visual complexity and that it does require manual switching back and forth between the modes, which can sometimes feel a bit awkward or confusing. 

The second option is to add context options to a right click (tap and hold on touch screens). In this method, the usual left click functionality remains as it is now, however when hovering near a node a right click will bring up a menu of options that can specifically applied at that location (i.e. node). The right click is context specific, so when not near a node then those options don't appear (or others might appear). Options that are available could include open node in new tab, etc. Google docs uses this kind of option a lot -- right click on something, see the options that are specifically available at the particular point (edit tools, etc.). The disadvantage of this kind of UX is that it is not visually apparent that this functionality is available; options are hidden until the right click is used -- not a problem when a user is used to it, but tricky at first. A couple advantages: it keeps the interface cleaner and less overwhelming, and it increases the power of the pointer - quicker and more logical use (fewer global modes, easier to present only available options for that particular click).

I hope that I have described these well enough. Let me know if it doesn't seem clear. I could create some visuals to illustrate.

**Comment by smurp** [comment]
This seems like it has been obviated by the clickable links in the snippet box.

This is true for everything except *orphan nodes* which only have `rdf:type` or the different kinds of labelling relations such as `foaf:name` or `rdfs:label`, etc.

**Comment by smurp** [comment]
This issue will be replaced by a new issue which describes a `node inspector` which is offered to users as a magnifying glass in the upper left corner of the display, which becomes visible when a node is being dragged (like the discard bin).
