### ISSUE TITLE
Problems switching datasets

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#17]
Problem:
- When switching between datasets, the new dataset doesn't always load. Often, only solution is to reload the entire page.

**Comment by cmiya** [comment]
- Still a **huge** issue. Noticed it a lot while preparing the script for testing. Was forced to open the tool in a new window when switching was required.

**Comment by smurp** [comment]
A 'reload' button now appears beside the dataset picker once one has been picked.  This button merely reloads the page.

0907117

**Comment by cmiya** [comment]
@smurp The reload button is not appearing for me.

**Comment by smurp** [comment]
My announcement was premature! I've just now restarted the servers so it
should show now.

On Fri, May 6, 2016 at 1:08 PM, cmiya <notifications@github.com> wrote:

> @smurp <https://github.com/smurp> The reload button is not appearing for
> me.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/17#issuecomment-217532362>
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by cmiya** [comment]
Okay, great! Thanks.
