### ISSUE TITLE
the graph label should not be selectable nor part of the tab sequence

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#173]
Make the graph label not part of the tab sequence (ie not able to be focused on) AND also make it not selectable.  These are two different things:

* [ ] Open the *Settings* tab, click within the Language Path field, press **tab** and see that the label for the graph is selected.  This should not be.  This is "being part of the tab sequence". Tabbing while in the `matching field` likely produces 

* [ ] The second thing can be experienced by graphing some data and then putting your mouse down at the bottom of the window and drag up as if to select the graph label text.  Note that it *can be selected*.  There is no purpose in this.  We should disable the selectability of the label text.  This is "being selectable".

**Comment by wolfmaul** [comment]
Tab order changed. 
Graph titles remain selectable
