### ISSUE TITLE
Open Annotation ontology fails to graph properly

### ISSUE THREAD

**Issue by wolfmaul** [cwrc/HuViz#179]
Some nodes are displayed without any links.

http://alpha.huviz.dev.nooron.com/#load+/data/oa.ttl+with+/data/owl_mini.ttl

* [x] there are two nodes called Motivation, one is a Thing, one is a Class instance.  Nicht so gut
* [x] the Class `Class` should be a Class, srsly
* [x] both subj and obj of rdfs:subClassOf triples should be marked as Class instances
* [ ] why is Class not appearing as a Class in video.ttl though? http://alpha.huviz.dev.nooron.com/#load+/data/video.ttl+with+/data/owl_mini.ttl

**Comment by SusanBrown** [comment]
Just a query which is hardly to the point of this issue, but is this the OA ontology or the WA ontology?
