### ISSUE TITLE
make HuViz render everything in sparqlTest1.ttl

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#182]
We want to be able to produce sparql queries, the output from which can be read by HuViz.

## Expected Behaviour
I loaded the file at https://raw.githubusercontent.com/cwrc/testData/master/sparqlTest1.ttl
I expected it to show the nodes for the people and for the occupation instances, and the edges for the occupation properties. I didn't expect it to do anything with classes since there weren't any.

## Current Behaviour
It seems to load but nothing shows. Tried in production and beta.

## Possible Solution
Kim wonders if the problem is that people are foaf:persons, but we use rdfs:label for other things, so I hoped it would be fine.  I didn't expect it to do anything with classes since there weren't any, but is it possible that it was because there were not any classes?

## Steps to Reproduce (for bugs)

1. Went to raw version of file.
2. Opened Huviz, and in the Command box, selected loading your own dataset and the CWRC ontology
3. Clicked to load
4. File seemed to load but nothing was rendered.
5. Tried in production and beta.

## Your Environment
* URL: http://huviz.dev.nooron.com/

* Browser Name: Chrome

* Operating System: MacOS

**Comment by smurp** [comment]
https://github.com/smurp/huviz/commit/98ec909149459de5c7a1f80989f24897453318ec
https://github.com/smurp/huviz/commit/77dea38866ad83eceb3117c6cd01880a00795360

**Comment by smurp** [comment]
* smurp/huviz@acaab3eb add make_nodes_for_literals setting which defaults to true

**Comment by smurp** [comment]
* smurp/huviz@f9dd60ff organized all xsd- and rdf-typed values under Literal in taxon_picker

# Wow!  That was a good one

This exposes in a very orderly way all sorts of details hidden in literal values.  

Try viewing the Open Annotation ontology for a treat.
http://alpha.huviz.dev.nooron.com/
