### ISSUE TITLE
Verb Set commands oscillate mesmerizingly

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#185]
When one performs a command such as `Activate All.` then the operation runs over and over again upon each update of the mouse over pickers in the command panel.  Racy! Obnoxious!

## Expected Behaviour
After completing the specification of a command the command should run and then the last entered term of the command (was it the verb or the set which was engaged last?) should be *disengaged* promptly, rather than running over and over again.

## Current Behaviour
Some commands run over and over again while the mouse is moving around over the pickers.

## The Real Mission
The true mission here is to impose greater discipline on the updating of the "Current Command" box, applying these principles:
* If only verbs are engaged (and nothing is selected) then clicking on a node, a class or a set will run a command immediately.
* If only a set is engaged then classes are disabled and clicking a verb runs the command immediately.
* With no verbs or sets engaged, clicking on a class will 1) add all, 2) add the rest or 3) remove all instances of the class from the Selected set depending on whether 1) none, 2) some or 3) all are already members.  The command will be either `Select CLASS .` for 1) and 2) or `Unselect CLASS .` in the case of 3).  If the class is `collapsed` then those commands will be either `Select every CLASS .` or `Unselect every CLASS .`
* Clicking nodes anywhere (ie on the shelf, in the graph or in the discards) while no verb is engaged performs `Select NODE` or `Unselect NODE` to alter the selectedness of the node.
* When there are Selected nodes (irrespective of whether they were selected individually or collectively) clicking on a verb immediately runs the command `VERB Selected .` 
* No longer are itemizations of the members of the Selected set included in the version of the command which appears in the Command History. Now the only time that the canonical version of the command (which appears in the History) has even a succinct indication of which nodes are having the verb applied (such as `VERB every Thing`) is as a result of the sequence 1) engage VERB 2) click on class or node.
* Another way to think of this is that now the members of the Selected set are treated like any other set in the canonical form of the command such, so it is now `Hide Selected.` just like `Hide Labelled.` and unlike the old canonical form `Hide Bob and Betty.`

## Steps
* [ ] remove the now redundant `recalc_english()` whose job was to make an effort to find the most succinct itemization of the selected set
* [ ] 
* [ ]

**Comment by smurp** [comment]
closed by https://github.com/smurp/huviz/commit/9cf96865375ee150ebd194d6dc8b7feb378a06e4
https://github.com/smurp/huviz/commit/482baaa85a6dc91d81c1008c3a8425f0b815b7dd

**Comment by SusanBrown** [comment]
woohoo!



On Jan 13, 2019, at 9:50 AM, Shawn Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


closed by smurp/huviz@9cf9686<https://github.com/smurp/huviz/commit/9cf96865375ee150ebd194d6dc8b7feb378a06e4>
smurp/huviz@482baaa<https://github.com/smurp/huviz/commit/482baaa85a6dc91d81c1008c3a8425f0b815b7dd>
