### ISSUE TITLE
Rename "Choose" to "Activate"

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#19]
PROBLEM:
-	The distinction between “choose” and “select” is unclear. The meaning of the two words might be too similar for users to distinguish between them leading to unnecessary confusion.

SOLUTION:
-	Susan has suggested re-labelling choose/unchoose as "graph/ungraph" and select/unselect as "activate"/de-activate.

*********

CURRENT DEFINITIONS:

*

CHOOSE:

Help Bubble: the help bubble for choose reads “put into the graph.”

Appearance: Chosen nodes are outlined in black

Definition:

- A chosen node is specifically designated by the user to be pulled into the graph.

- Nodes can also be pulled into the graph automatically by clicking to see the links associated with a node in the Edges of Selected Node bar. For instance, if I select Person under the Classes bar and then click connectionwithJob under the Edges of the Selected Nodes bar then the nodes associated with Jobs will be dragged into the graph.

- The subject of a dataset (we might call these the node hubs; for example, R. M. Ballantyne in the ball.rm dataset) will also be automatically pulled into the graph by dragging in an associated node. A node that is not a hub cannot exist in the graph on its own; it will always drag in an associated hub. (*SIDENOTE: A dataset can have multiple hubs (see: the Bronte dataset), but can a dataset have no hubs at all? How might this change the “rules” of node behaviour?).

- But those automatically dragged in nodes are NOT chosen. In fact, an automatically generated node is considered to be both graphed and unchosen.

- Chosen and unchosen nodes behave differently. According to Shawn (see email exchange), “a chosen node will stay in the graph when an unchosen node it is linked to is removed.  That is not true for unchosen nodes.” (*NOTE: Has anyone been able to replicate this behaviour? Is this a useful function? If so, is it important to keep the name as is, in order to distinguish between being graphed and chosen? Or does it matter?)

*

SELECT:

Help Bubble: There is no help bubble for select.

Appearance: Selected nodes are bolded (a darker colour and slightly bigger)

Definition:
- Selecting a node allows you to see all of the links associated with it. These links (known as edges) are displayed in the Edges of the Selected Node bar.
- You do not have to select a node to apply a verb (like shelve, discard, label or choose) to it. BUT the select function allows you to work with multiple nodes at the same time. This function is especially helpful if you are working with a large dataset.
- *NOTE: You can make changes to the entire dataset (without selecting it) by clicking the All button under the Sets bar.
- Almost any nodes can be selected, including those that are graphed, shelved or in the discard bin. (The only nodes that cannot be selected are those that are hidden, which means they have been removed entirely, at least until they are retrieved).
- If no verbs have been selected (for instance, at the start of a session or when a dataset has been newly reset and the Current Command bar is empty), clicking a node on the shelf will automatically select it.
- Nodes can also be selected by:
  1) Clicking the select button on the Verb bar and then clicking a node (the verb select will show up in the Current Command bar).
  2) Clicking different categories of classes (such as person, place or GeographicArea) on the Classes bar.  *Note: classes can be expanded to show sub categories by clicking the arrow beside the name. Unexpanded classes will have an arrow pointing horizontally, while expanded classes will have an arrow pointing down
- You can deselect a node by clicking the deselect button in the Verb bar.

**Comment by cmiya** [comment]
This is the meaning of the terms, as I understand it. But if you have a different concept of their definition/functionality - feel free to post! I think we're still trying to sort it out.

**Comment by cmiya** [comment]
Looking over the Quick Reference Guide, I feel like there is some overlap between "UnChoose" and "Shelve," "Hide" and "Discard." Applying anyone of these actions to a Node automatically UnChooses it (as Chosen nodes can only exist inside the central graph). If we could eliminate "UnChoose" this would simplify the Toolbox, especially if we decide to change "Choose" to "Graph" (The meaning of "UnGraph" again feels too close "Shelve," "Hide" and "Discard.")

**Comment by smurp** [comment]
I would argue for keeping the term `select` because it really is like a block of selected text in a word-processing document, or the selected set of cells in a spreadsheet -- **selected nodes in the graph are the object of the next command!**

**Comment by smurp** [comment]
Even hidden nodes can be selected.

With the dataset `shakwi`, do:
* `hide Settlement`
* `select All`

Note `Selected (41)` in the set picker.

**Comment by cmiya** [comment]
When you mean you can't seem them - does that mean the nodes will physically disappear from the graph, BUT they will still show up under the tally of different classes in the Class Bar? Or will they also be eliminated from the classes tally?

**Comment by smurp** [comment]
Proposal: we just make **Configuratable Terminology Sets** see #39 and mark this closed.

**Comment by smurp** [comment]
Sorry, didn't mean to actually close it yet, merely propose that!

**Comment by jsmithelford** [comment]
Replace "choose" with "activate" (as in: activate the graph--the rest will be made clear in documentation.

**Comment by smurp** [comment]
This is just like #19 and #20 and I would suggest that rather than the time
being put into chasing around in the code for all internal uses of the term
in various data structures where it appears in a couple of different forms,
that we modify #39 to continue to abstract out the presentation of the verb
and set names but not make the terminology sets interchangeable, just have
a hardcoded set of the user-visible "pretty names" within the code.  This
is a better investment of the time (approximately 4 hours) because what we
get for it is the ability to change any of the verb or set names
trivially.  How this suggestion differs from the existing #39 is it does
not include making it easy for users or administrators to swap in and out
whole *Terminology Sets* for A/B testing, it just makes it easy for a coder
to change terms in one place, and sets the stage for the eventual
swappability.

On Thu, Oct 1, 2015 at 11:14 AM, cmiya <notifications@github.com> wrote:

> Assigned #19 <https://github.com/cwrc/HuViz/issues/19> to @smurp
> <https://github.com/smurp>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/19#event-424525945>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by cmiya** [comment]
Approximately how long would it take to change "Choose" to "Activate?"

We all agree that interchangeable terms is something we eventually want to do. However, our objective right now is to stay on schedule and focus only on tasks that are absolutely necessary. What we want to avoid at all costs is becoming bogged down by secondary tasks and missing the deadline. By all means, once the milestone tasks are completed (perhaps this will happen in advance of the deadline) - let's do this! But for now... I'm inclined to keep our focus as streamlined as possible.

**Comment by smurp** [comment]
It would probably take about 2 hrs to change the ~200 instances of the
various forms of the term.  There is the possibility of cryptic bugs.  The
work is throw-away, in that it accomplishes a very small (and possibly
impermanent goal) and provides no "force magnification", ie it is not a
"feature". Any subsequent alteration of that or any other user-visible term
would take the same degree of effort.  The hardcoded version of #39 I'm
proposing would take about 4 hrs but would take us on a path that would
make it trivial to make any change to any term and even eventually expose
that power to administrators and/or users.  This is a pretty clear
situation, I think.

On Thu, Oct 1, 2015 at 4:20 PM, cmiya <notifications@github.com> wrote:

> Approximately how long would it take to change "Choose" to "Activate?"
>
> We all agree that interchangeable terms is something we eventually want to
> do. However, our objective right now is to stay on schedule and focus only
> on tasks that are absolutely necessary. What we want to avoid at all costs
> is becoming bogged down by secondary tasks and missing the deadline. By all
> means, once the milestone tasks are completed (perhaps this will happen in
> advance of the deadline) - let's do this! But for now... I'm inclined to
> keep our focus as streamlined as possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/19#issuecomment-144875311>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by cmiya** [comment]
Okay, if it's only 2 more hours with a much higher value for time then it makes sense to go with #39.

@jsmithelford and @ilovan, any thoughts on this?

**Comment by jsmithelford** [comment]
This seems to make sense, as long as it is just the four hours.

**Comment by ilovan** [comment]
I agree with @jsmithelford .
@SusanBrown , what's your take on this?

**Comment by cmiya** [comment]
I'm not sure how this would affect documentation in DITA. Is it relatively simple to allow for fluid terminology in the instructions? @ilovan what would be the time estimate for these extra steps? (I would probably take on this task myself)

**Comment by SusanBrown** [comment]
I think we should go with the solution of being able to make the terms configurable 
(although I have to admit to being surprised that swapping out terms would take that much manual work) but Shawn please check in immediately if you are not able to deal with this within the 4 allocated hours. 

Chelsea, could you please make another ticket with the labels that we've selected, chosen, and want to activate for particular actions?

**Comment by smurp** [comment]
The system as currently architected has those term scattered all over the
code-base, indeed with some variant versions -- systematically, but with
prefixes or suffixes in certain related datastructures -- so that means
that just changing the name from one to another means a bunch of fiddling
across a bunch of files with a handful of variants spelling.  Instead if we
just add a capability to display a "pretty name" (the one to present to
users) in those few places where users are exposed to what is going on
behind the curtain, then it is actually less work.  That mapping will
initially be hard-coded so editing the source code is required to change
the pretty-name, but at least that will happen in one and only one place.

On Mon, Oct 19, 2015 at 10:22 AM, SusanBrown <notifications@github.com>
wrote:

> I think we should go with the solution of being able to make the terms
> configurable
> (although I have to admit to being surprised that swapping out terms would
> take that much manual work) but Shawn please check in immediately if you
> are not able to deal with this within the 4 allocated hours.
>
> Chelsea, could you please make another ticket with the labels that we've
> selected, chosen, and want to activate for particular actions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/19#issuecomment-149267186>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by ilovan** [comment]
To answer Chelsea's question about how changeable terms would affect documentation, I think we could handle it with some DITA content profiling, but it would be a bit of a learning curve for both of us.

**Comment by cmiya** [comment]
So, as per the recommendations of @smurp and with @SusanBrown's permission, I'm going to close this issue for now, and substitute it with issue #39, which will be linked to the Milestone.
