### ISSUE TITLE
loading difficulties in alpha and beta

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#191]
## Expected Behaviour
Loading from github not working; loading from menu sometimes not working

## Current Behaviour

- loading by clicking on this link works: http://alpha.huviz.dev.nooron.com/#load+https://raw.githubusercontent.com/cwrc/testData/master/sparqlTest1.ttl+with+http://sparql.cwrc.ca/ontology/cwrc.ttl
- loading the same file from the dropdown sometimes works
- loading by dragging a raw file (including the same one) from github doesn't work at all and leads to a loading message that sits frozen on the screen

![image](https://user-images.githubusercontent.com/545952/47197036-bb0f4b00-d331-11e8-99ae-0da99e95dd41.png)

**Comment by smurp** [comment]
All three modes are working on Alpha and Beta at this time.

**Comment by smurp** [comment]
When I closed this yesterday it was all working, but now these two urls are doing "Error: Bad Request while fetching": 
* http://alpha.huviz.dev.nooron.com/#load+https://raw.githubusercontent.com/cwrc/testData/master/demoData/REED_Elizabethan_sample.ttl+with+/data/cwrc_wo_genre.ttl
* http://alpha.huviz.dev.nooron.com/#load+https://raw.githubusercontent.com/cwrc/testData/master/sparqlTest1.ttl+with+http://sparql.cwrc.ca/ontology/cwrc.ttl

**Comment by smurp** [comment]
![badrequestwhilefetching](https://user-images.githubusercontent.com/774119/47368155-69741100-d6e1-11e8-878d-672abc06c1e1.png)

**Comment by smurp** [comment]
* smurp/huviz@288be6c3 resolve fight between SPARQL and the reload button by breaking SPARQL

Hey @wolfmaul tomorrow let's look together at how the SPARQL menu is tying into things.
