### ISSUE TITLE
comment literal mishandling revealed by REED dataset

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#195]
In http://alpha.huviz.dev.nooron.com/ when loading the REED dataset HuViz goes to the debugger with `id: comment state: unshowing old_state: empty TypeError: Cannot read property 'classed' of undefined`

This is associated with the setting `@make_nodes_for_literals`

## Current Behaviour
HuViz goes to the debugger when loading the REED dataset

**Comment by SusanBrown** [comment]
Is this the REED dataset from the dropdown? Kim can't see the error? Fixed? If not pls describe more fully @smurp

**Comment by SusanBrown** [comment]
Also so we need to ensure this is not a problem in the dataset?

**Comment by smurp** [comment]
I've removed places where we drop into debugger
