### ISSUE TITLE
Reformat Snippet Boxes to include full URLs

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#199]
The snippet boxes (that appear when you click on the predicate) currently show the triples, but it would be great if they could have the URL. Could we include:

- Subject
- Property
- Source Graph
- Full URLS 

## Expected Behaviour
Format as a definition list. 
Make the URLs clickable.

## Current Behaviour
The snippet boxes currently show the triples.

**Comment by smurp** [comment]
@wolfmaul  Basically the idea is make the little box you see when you click on an edge show an HTML <DL> list with the DTs being Subject, Predicate, Object and Graph
and the DDs being the full, clickable URLs to the resources. In the case of the literal object values, just display them in a nice way.

**Comment by smurp** [comment]
https://github.com/smurp/huviz/commit/948ef56ab13a12379094aeb25f577e5351d9de31

**Comment by smurp** [comment]
Deployed to Beta

**Comment by smurp** [comment]
This thing is super useful, btw.
