### ISSUE TITLE
Update the Quick Guide to be more user-friendly (3 hrs)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#2]
CURRENT PROBLEMS:
- The quick guide should help “sell” the tool, explaining its purpose in clear and concise terms. Would a novice user understand terms like “semantic language,” “rdf triplets” or “ontology”?
- Some of the instructions are out-of-date. There is no “do it” button anymore, for instance.
- The instructions refer to tool-specific terminology like “nodes” and “edges,” but do not explain what they are. Only two verbs (“choose” and “unchoose”) are defined.
- The instructions lack screenshots or visual cues. This is especially important for a tool like huviz with a complex interface.

SOLUTIONS:
- Novice Users tend not to explore lengthy documentation. Best to keep the Quick Guide short and to the point
- Using the Scikit quick guide as a model, organize the quick start into three sections (with section titles as hyperlinks at top of page):

1) What is HuViz? (description adapted from tool profile on CWRC project page)
2) Key terminology
3) Getting started → brief intro to the key commands, organized into numbered steps

**Comment by smurp** [comment]
see many changes to the quickstart guide in the last couple of commits https://github.com/smurp/huviz/commit/4da9a4d

deployed
