### ISSUE TITLE
Labels from chosen ontology are not always rendering

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#200]
We want the labels to load from the preferred ontology wherever available.

## Expected Behaviour
- If there is a skos:label available in the preferred language, HuViz should use it. 
- If not it should fall back on another label from another language, if available.

## Current Behaviour
labels for religions are not rendering (see screenshot) even though they are available in the ontology

## Steps to Reproduce (for bugs)
file used: 
![image](https://user-images.githubusercontent.com/545952/47611568-93f5ff00-da3e-11e8-8173-581064011ad2.png)

**Comment by smurp** [comment]
It would greatly speed debugging this if we had confidence that we were looking at the right situation.  Could you paste a link to the "Reload URL" so we know how to reproduce the problem?

A cute trick for this is to, when you load some data, press the little reload button beside the dataset and ontology names.  That way the URL in the location bar shows how to get at the current situation.

Hmm.  This suggests a "well" from which you can drag or copy the current "Reload URL".

**Comment by SusanBrown** [comment]
Nifty: I will try to get used to doing this.

Here it is: http://beta.huviz.dev.nooron.com/#load+https://raw.githubusercontent.com/cwrc/testData/master/jewish_novelist_biographies.ttl+with+http://sparql.cwrc.ca/ontology/cwrc.ttl

If you activate Grace Aguilar and label all the nodes you will see a bunch of nodes such as catholicism, christianity, juadaism, that are not rendering with labels.

{and the files are loading now the extension is there. doh.}

![image](https://user-images.githubusercontent.com/545952/47758669-6600fc80-dc82-11e8-9c3b-7f57ce4a0a90.png)

**Comment by smurp** [comment]
![religionmultistring](https://user-images.githubusercontent.com/774119/48833267-4ccc0700-ed7b-11e8-9c5f-0e8871df633b.png)

http://alpha.huviz.dev.nooron.com/#load+https://raw.githubusercontent.com/cwrc/testData/master/sparqlOutputs/jewish_novelist_biographies.ttl+with+http://sparql.cwrc.ca/ontology/cwrc.ttl

**Comment by SusanBrown** [comment]
Reopening this because not all labels are rendering, for instance the label for this Class:
<http://sparql.cwrc.ca/ontologies/cwrc#SpatialContext> 

This is evident in this graph:
https://raw.githubusercontent.com/cwrc/testData/master/sparqlOutputs/AguilarSpatialContexts.ttl
