### ISSUE TITLE
Re-organize Drop Down List 

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#202]
The list and items in the drop down list are getting quite dated, and we'd like to re-organize them in order for Geoffrey's class to be able to test HuViz.

Could we please re-organize the Drop Down list as follows:

**Top**: Change “CWRC Data” to read “CWRC Data” (newest)
**Then**: list the Ontologies
**Then**: have a line or a heading before the list of individuals starts that says something like “Older datasets” and list everything else (older Orlando datasets, etc) there.

Under “CWRC Data” (newest) we would like the following changes:

**Title of Dataset | Keep/Delete/Change/Add**
-- | --
DH2017Montreal.tll | Keep & Change title → WoolfsOrlando.ttl
HuVizSharp2017 | Delete
REED Elizabethan Sample | Keep
Levy Bio Triples | Keep & Change title → Levy Biography Triples
CanAuthorsBiography | Keep & Change Title → CDNAuthorsBiography
SparqlTest1 | Delete

Under Ontologies we would like the following changes:

**Title of Ontology | Keep/Delete/Change | Change to...**
-- | -- | --
Orlando Ontology | Keep | Orlando Ontology (for older datasets)
CWRC Ontology | Keep |  
CWRC Ontology sans Genre | Delete |  
Orlando Ontology - Sexes under person | Delete |  
Owl Mini | Keep |  
Schema.Org | Keep |  
FOAF | Keep |  
OA | Keep |  
VidOnt | Keep |  

The older datasets can stay as they are until we produce more (clean, newer) ones. Cheers!

**Comment by SusanBrown** [comment]
Also, can we please add the following datasets under the CWRC data section:

Jewish novelist biographies https://raw.githubusercontent.com/cwrc/testData/master/jewish_novelist_biographies

Unitarian novelists biographies
https://raw.githubusercontent.com/cwrc/testData/master/unitarian_novelist_biographies

I have not been able to test either of these from the github versions because of the loading but, but both of these load in beta from files on my computer.

**Comment by smurp** [comment]
HuViz (like most things) expects files to have extensions so it knows how to digest them.  If jewish_novelist_biographies and unitarian_novelist_biographies had a .ttl extension I believe they would load correctly.

**Comment by smurp** [comment]
Wow the unitarian novelists is a big graph!

**Comment by smurp** [comment]
Having trouble with control over the ordering of the menu sections, can we leave that?

**Comment by SusanBrown** [comment]
@smurp I can't get either of the sparql datasets (jewish and unitarian) to load from the menu in beta. Do they work for you?

![image](https://user-images.githubusercontent.com/545952/47820840-18919780-dd35-11e8-9b45-b38d937c5199.png)

**Comment by SusanBrown** [comment]
Sorry--my bad--we moved the files into a folder tonight, hence the breakage:

https://github.com/cwrc/testData/blob/master/sparqlOutputs/jewish_novelist_biographies.ttl

https://github.com/cwrc/testData/blob/master/sparqlOutputs/unitarian_novelist_biographies.ttl

Apologies!

**Comment by antimony27** [comment]
I think perhaps the links are incorrect? 
The error I am getting is:
![image](https://user-images.githubusercontent.com/11494469/47932451-21ef4100-dea8-11e8-8210-9581d94502b5.png)
but the datasets are actually in the folder here:

https://github.com/cwrc/testData/tree/master/sparqlOutputs

If I am correct, can we get those changed @smurp ?

**Comment by SusanBrown** [comment]
Yes, thanks for figuring it out, Kim. I think I flagged this already but then forgot what the problem was. need more sleep. I think the URLs for the files just need to be changed.

**Comment by antimony27** [comment]
I'm still getting the following error while trying to load these two datasets:

![image](https://user-images.githubusercontent.com/11494469/48039585-6cd8b500-e143-11e8-9428-36d255066ec2.png)

Do they load for you @wolfmaul ?

**Comment by antimony27** [comment]
@SusanBrown They work in alpha! @smurp is going to push them to Beta right now. Closing.
