### ISSUE TITLE
Why is coreWork displaying as grey in the class picker?

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#204]
See how `coreWork` and `coreExpression`.

http://alpha.huviz.dev.nooron.com/#load+https://raw.githubusercontent.com/cwrc/testData/master/demoData/WoolfsOrlando.ttl+with+http://sparql.cwrc.ca/ontology/cwrc.ttl

**Comment by antimony27** [comment]
This seems to be remedied. Can you confirm @smurp ?

**Comment by smurp** [comment]
I don't think we've fixed this.  

When a triple comes in which tells us that a node is of a particular class then the class is promptly added to the Class Picker.  If a subsequent triple clarifies that the node ought to be understood to be a member of a *different* class then the change is made but the now childless class is not dislodged from the picker.  This is tied up with the business about displaying nodes which are in multiple classes as pies.
