### ISSUE TITLE
Pick or provide bug

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#205]
When a problem arises with a file and the command box reappears after the feedback on the error, the box for dragging in a dataset is no longer present.

## Steps to Reproduce (for bugs)
1. In beta, pick Provide a new dataset; pick CWRC ontology.
2. Load a file with a .txt extension. Get helpful error message.
3. When message disappears and command box is again accessible, the box for adding the file has disappeared:
![image](https://user-images.githubusercontent.com/545952/48160465-ed172b80-e2a5-11e8-98f5-01d315f53eb6.png)

**Comment by smurp** [comment]
@wolfmaul

**Comment by SusanBrown** [comment]
Closing for now. We haven't noticed this recently although it may reappear when the file loading bug is fixed.
