### ISSUE TITLE
labels and classes should not show as edges

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#206]
I believe this is just a confirmation of what we talked about in our last meeting, but I want to confirm because Kim and I understood differently:

labels should be rendered as labels for the nodes, not shown as edges
ditto for classes, which should be indicated by the class picker and the colour of the nodes
 (they used to act as requested but something changed)

this should be the default. if easy to make it a setting to show these as edges, that would be dandy (and it would be 2 separate settings as one might want one but not the other; for labels it could show all labels in all languages, not just the preferred ones--but only do the settings stuff is it's really trivial to do so)

**Comment by antimony27** [comment]
@smurp Susan is planning to showcase this at a small event in California next week, so let's put this right to the top of the priority list (changes to Zenhub coming asap!)

**Comment by smurp** [comment]
http://alpha.huviz.dev.nooron.com/#load+https://raw.githubusercontent.com/cwrc/testData/master/sparqlOutputs/jewish_novelist_biographies.ttl+with+http://sparql.cwrc.ca/ontology/cwrc.ttl

Note that after `Select All Thing.` the predicate picker does not show `type` as one of the available edges.

To turn *ON* the display of class-instances relationships (ie the use of the `rdf:type` predicate) change the setting **Show class-instance relationships** before loading the data.

Though we are now seeing the turning OFF of class-instance relationships working properly, the fact that turning them ON only shows 7 `type` edges (ie 6 **Natural Person** instances) shows that cwrc/HuViz#120 should be re-opened and that not all `rdf:type` relations are being displayed as edges even when **Show class-instance relationships** is turned enabled.
