### ISSUE TITLE
Create a Node Inspector

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#207]
Provide a way for users to inspect the information associated with each node.

## Expected Behaviour
We have seen a problem with orphaned nodes, and expect to see more in the future. What if we could drag an orphaned node to an area of the screen - could the nodes' URI now appear? its Type?

It could be like the discard bin, just appear faintly in the background, perhaps like a magnifying glass. 

## Current Behaviour
Right now we are getting most of the information on nodes from clicking on the edges between them. This would provide another layer of information discovery. 

* [x]  expand literals to their literal value rather than showing the hash
* [x] to prevent multiple inspectors per node attach a property to a node with a reference to its inspector and bring it forward if another inspector for that node is requested and remove the reference when the inspector is closed
* [ ] When an attempt is made to inspect a node whose inspector is already visible the `hilight_dialog()` method should bring the desired inspector to the top and perform a little CSS animation (wiggle, bounce, etc) to bring attention to it.  This will give the edge inspector the same benefit.

**Comment by wolfmaul** [comment]
There is still a bug in how some nodes are handled. It causes there to be a 'break' in the right-click, left-click and then creates immovable boxes (the proper jquery registration doesn't happen) and duplicates that are not properly cleared. 

Also bad break with # in id messes up jquery. Example: load Open Annotation and select www_w3_org_ns_oa# - hash sign is causing grief.

**Comment by SusanBrown** [comment]
@smurp also thinks that there may be problems with displaying the content of actual literals

**Comment by smurp** [comment]
The synthetic hashes used to act as IDs for literals appear directly in the Node Inspector. The literals should appear directly in the Node Inspector (and the Edge Inspector too) rather than have their hashes appear.

**Comment by smurp** [comment]
Literals now display pleasantly in the node inspector, including:
* hovering over a literal value shows the data type of the value (eg `xsd:date`)
* long or multiline values show in a blockquote

**Comment by smurp** [comment]
@antimony27 @SusanBrown The node inspector is now unique per node, ie you won't get two of them if you try to inspect the same node twice.  You *can* have multiple inspectors open simultaneously though.

**Comment by smurp** [comment]
I've moved the hilight effect out into its own issue since it relates to both node and edge inspectors. https://github.com/cwrc/HuViz/issues/299
