### ISSUE TITLE
Change the word "graph" to "source" in the Snippets box

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#208]
Users may expect to see another graph when they click on the bottom link here:

![image.png](https://images.zenhubusercontent.com/5a690dea4b5806bc2bc43079/41dd222a-2eb5-423b-b38f-1a10896c3932)

Can we change this to read "source" so they aren't surprised when it takes them to the data?

**Comment by smurp** [comment]
closed with smurp/huviz@fe9555ba7
