### ISSUE TITLE
Discard bin obscured by command tab

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#21]
PROBLEM:
-   When the subcategories in the Classes and Edges of Selected Nodes bar are expanded, the discard bin and its contents are completely obscured by the command tab (this is true when accessing the HuViz tool from my laptop – a regular-sized Macbook – and I imagine other laptop users will experience the same problem)

SOLUTION:
-   Perhaps move discard bin to another area? (Would the bottom left work?)
-   OR ensure that the red discard bin is always visible (dot moves further down if obscured by tab)
-   Other suggestions?? Which solution would work best?

**Comment by ilovan** [comment]
How about: turn it into a small icon, somewhere at the top of the area rather than at the top. Show that there are items in the bin by adding a tiny red dot to the bin icon. Make clicking on the bin icon expand the bin and display/list all the items in the bin.

**Comment by cmiya** [comment]
I think the only issue in putting it at the top is that this area currently gets filled up by the snippet windows when multiple boxes are open.

**Comment by cmiya** [comment]
I'm finding that, at least on regular laptop screens, the discard bin in the bottom right is totally obscured. It's especially an issue because we don't have a minimize button any longer - not sure why this is? The page scroll has no effect as the bin is actually *under* the command tab, not below.

<img width="1274" alt="screen shot 2017-09-08 at 1 41 36 pm" src="https://user-images.githubusercontent.com/13421476/30228531-77b50e10-949b-11e7-8506-3d780010f883.png">

**Comment by smurp** [comment]
see #61

**Comment by antimony27** [comment]
This issue if being cleared up in #104
