### ISSUE TITLE
scale nodes by the number edges they have

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#211]
## Expected Behaviour
* [x] Make nodes larger as a function of how many edges they have.  
* [x] Make a Setting to adjust the factor by which nodes grow as a function of edge count (like the current `line edge weight` setting but for node diameter

## Current Behaviour
Currently there is no way to tell at a glance which nodes are most interesting from a connectivity perspective.  As a consequence the eye is not drawn to natural nodes of interest and `Walk`ing is less efficient.

**Comment by SusanBrown** [comment]
Both these things are done, are they not @wolfmaul ?
