### ISSUE TITLE
Put greyed-out word: {node name} in like box instead of blank. (10 min)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#23]
-	Currently not seeing "Hover/Help" bubble over "like" box. What is the function of the like box? Is this a way to search through nodes or links? Is it an open text search? Can't seem to figure it out... Is it currently working? (Or will this be sorted out with the new ontology?)

**Comment by smurp** [comment]
The **like box** add a *like clause* to the command and has the impact of constraining the **object phrase**, for example:

     label All like 'London'

For typing in the like box to have any impact the command must be complete (ie have an **object phrase**) and be executed.  We might want to add the feature that the matched nodes would be hilighted in some way during typing, see #34

The **like box** respects normal JavaScript regular expressions, which are lightly documented and provided with a playground here http://regexpal.com/

**Comment by jsmithelford** [comment]
Put greyed-out word: node in like box instead of blank.

**Comment by ilovan** [comment]
@smurp , can you quote for this ? thx

**Comment by smurp** [comment]
Would "search string" make more sense?

On Thu, Oct 1, 2015 at 9:20 AM, jsmithelford <notifications@github.com>
wrote:

> Put greyed-out word: node in like box instead of blank.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/23#issuecomment-144777378>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by SusanBrown** [comment]
we understood it to be a search on the names of nodes only, not the snippets or edge content, so we don’t want to imply that it’s a more general search.

we could use “search on node name” if we want to be more specific

**Comment by cmiya** [comment]
Looks good.

But I'm having trouble "choosing" the search results (possible bug??)

As I understand it, the Like bar is not only supposed to convey information (through labels), but also allow the user to manipulate specific nodes. For instance, I'm currently testing the Augusta Ada Byron dataset. First, I want to see how many nodes have "Byron" in the node name. As mentioned before, typing "Byron" in the like bar and then simply clicking a verb has no effect. In order to see the Byron labels, I have to type "Byron," then click "Label" and finally click "All." I think automatically selecting "All" when searching was a feature that we discussed implementing in the future. For now, it's fine to enter it manually. Most of the verbs (label/unlabel, hide/unhide, select/unselect) work using these steps... EXPECT for "choose." Clicking "choose" and then "All" causes all of the nodes to be graphed, not just the Bryon ones. Is there a reason for this, or is it a possible bug?
