### ISSUE TITLE
Clean up cryptic terms in Sparql end point pick list

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#238]
Maybe we need to understand better how it gets populated?

![image](https://user-images.githubusercontent.com/545952/50852079-9a60fb00-134c-11e9-8c66-84d6c53fcc9d.png)

**Comment by SusanBrown** [comment]
For the paper, we need to know which endpoints we should say it can pull from. CWRC, DBpedia yes, but I've tried the bottom two WW1 and OpenU and not been able to get anything to load. 

I get "Cross-Origin error while fetching http://data.open.ac.uk/query"

DBpedia is loading

@smurp can you clarify?

**Comment by SusanBrown** [comment]
I do recognize that in theory it can pull from any endpoint if one inputs the URL. How extensively has this been tested? I know I haven't tried it.

**Comment by smurp** [comment]
@wolfmaul has done the majority of the work on this feature and I've just spoken with him about it.  Apparently those "UnknownX" endpoints came principally from the set of endpoints linked-to over on the CWRC website.  He'll straighten up the naming and/or the items asap.  He hasn't recently tested the providing of new endpoints but will do that too.  A heads-up about SPARQL endpoints –for all the standardization of the query language there are still unstandardized aspects which complicate simply connecting to one and establishing communications.  Apparently things like whether they are properly configured for CORS; what formatting is used to submit queries and what formatting of responses is available are not trivially negotiated – it could be that some of these details might need to be configured by the user on a per-endpoint basis or that we will have to figure out how to do the handshaking needed to determine those matters.  Further, our testing seems to show that endpoints have a tendency to go up and down rather sporadically.  It could be that this is a performance issue that is the consequence of the indeterminate computational complexity of SPARQL queries – an inherency of the technology as far as I know.

**Comment by smurp** [comment]
@SusanBrown see resp above

**Comment by antimony27** [comment]
From what I can see in alpha, this is complete. Closing.
