### ISSUE TITLE
Can't get graphed nodes to label

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#239]
In alpha, I can't get nodes to label. Huviz seems to freeze at the point in the screenshot. Have replicated this problem. 

## Steps to Reproduce (for bugs)
1. load jewish women novelist biographies dataset
2. play with settings (dark theme, size of fisheye radius)
3. drag in Aguilar, Monetefiore and Dacre
4. click on "Graphed" in Set picker, then click "Label"
5. Result is as in screenshot. Note that the circular progress indicator by the commands keeps running.

![image](https://user-images.githubusercontent.com/545952/50878170-5b11c900-13a3-11e9-9080-fb86f2389a81.png)

**Comment by smurp** [comment]
I believe this was fixed in the last couple of hours.
