### ISSUE TITLE
Red screen from walking and labelling too many nodes?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#243]
Got the alarming screen by asking it to walk and label all graphed nodes when 171 nodes were graphed
dataset: unitarian
onto: cwrc

![image](https://user-images.githubusercontent.com/545952/51163017-5303ce80-1866-11e9-92ed-a188ad428725.png)

**Comment by SusanBrown** [comment]
Also wondering why nodes were turning from circles to squares @smurp

**Comment by smurp** [comment]
Yes, boxed labels look like that when not labelled.

**Comment by smurp** [comment]
Some causes of this are now fixed.  

1. Replay of `Walk` was bugged and fixed.  
2. It is illegal to Walk Sets or Classes and there are now "shields" up to prevent that as soon as the `Walk` verb is engaged.  

There is still a way to step in that second puddle though: engage a Set (or add anything to the Selected Set) and then click on `Walk`.  This triggers the nonsense of a path that starts from many nodes and gets all squirrelly.  We'll add a "shield" for verbs which shouldn't be applied to Sets.  At this point that is only the verb `Walk`. 

PS In contrast try engaging `Wander and Label` and clicking on Sets or Classes.  Not sure exactly what the point is, but it is a fun way to survey the data.

**Comment by smurp** [comment]
I think I've solved the remaining problems with Walk.  Here is a script to show it.
[WalkAbout.txt](https://github.com/cwrc/HuViz/files/2770576/WalkAbout.txt)

**Comment by SusanBrown** [comment]
hurray!
