### ISSUE TITLE
Geonames authentication  error message not always accurate

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#244]
Got this when I had cut and pasted it from what was already in the box. Happened more than once that I put in the right user name and got the error. Realize that it may network connection or whatever. So the best we can do might be to revise the message to make it clear that it is sometimes a false negative.

![image](https://user-images.githubusercontent.com/545952/51163163-cc9bbc80-1866-11e9-8e37-b6d675f208dc.png)

**Comment by SusanBrown** [comment]
What about something like 
"Oops! We geonames doesn't seem to recognize this account. If you're confident it's right, try again as this sometimes happens. 
If you haven't got a geonames account, then 1) create a new account....etc.

**Comment by antimony27** [comment]
Does not reflect current state of affairs.
