### ISSUE TITLE
Nodes sticking to shelf - (extreme edition)

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#245]
When I pull a node into the center of the shelf, most of the nodes that would normally follow it in are sticking to the shelf.

## Expected Behaviour
The nodes should follow the node being dragged into the shelf and form a graph

## Current Behaviour
Sticking to shelf: 
![image](https://user-images.githubusercontent.com/11494469/51164855-301bef00-1853-11e9-9e7f-df33d4d84ef1.png)

## Steps to Reproduce (for bugs)
1. loaded 
![image](https://user-images.githubusercontent.com/11494469/51164946-796c3e80-1853-11e9-96cc-f01b1c9ae41d.png)

2. Dragged Henry Fielding into the center of graph. 
3. Everything stuck to shelf.

![image](https://user-images.githubusercontent.com/11494469/51164925-707b6d00-1853-11e9-8603-0faece097de9.png)

* URL: http://alpha.huviz.dev.nooron.com/

**Comment by smurp** [comment]
I will attend to this immediately.  I was focused on dealing with the loading from the menu issue.
