### ISSUE TITLE
Stray node

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#247]
## Expected Behaviour
Expect nodes to behave similarly unless interacted with.

## Current Behaviour
One node is straying way off from the others and hugging the shelf so tightly that it often appears to be on the shelf, particularly when one tries to select it.

## Steps to Reproduce (for bugs)
1. Load Unitarian dataset
2. History file attached
3. Kim and I think the stray node is LOC SH for needlework, although from the history it appears to be the one for Music. However, I think that is just because it was right next to Music and I was unable to inspect it and kept getting Music instead.

[HuVizScriptOddNodeOut.txt](https://github.com/cwrc/HuViz/files/2775957/HuVizScriptOddNodeOut.txt)

**Comment by smurp** [comment]
This isn't a problem with node clicking. It is a problem with the node.  It looks like there is something fishy about the Music node data which is triggering an unfortunate response in HuViz behaviour.  I shall investigate.

**Comment by SusanBrown** [comment]
Are you sure it’s not Needlework?

I’d look at both.


On Jan 19, 2019, at 8:37 PM, Shawn Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


This isn't a problem with node clicking. It is a problem with the node. It looks like there is something fishy about the Music node data which is triggering an unfortunate response in HuViz behaviour. I shall investigate.

**Comment by smurp** [comment]
This is likely caused by SortedSet problems, as at the root of #225

**Comment by smurp** [comment]
This is resolved AFAICT.  Part of the problem was that an empty string as an object value was not being dealt with sensitively enough.  That was damaging sorting, which was exposed as this issue with Needlework and Music.
