### ISSUE TITLE
Security vulnerabilities 

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#252]
Github has flagged two security vulnerabilities. Do we need to be concerned about them?

**Comment by smurp** [comment]
Heavens no!  Huviz doesn't have any write access anywhere nor is HuViz embedded in anything which does...  

But of course I will get around to adjusting the versions of `express` and `jqery` employed so github's pesky squawking is squelched.

**Comment by SusanBrown** [comment]
Thanks! That’s sort of what I thought.


On Feb 7, 2019, at 3:07 PM, Shawn Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Heavens no! Huviz doesn't have any write access anywhere nor is HuViz embedded in anything which does...

But of course I will get around to adjusting the versions of express and jqery employed so github's pesky squawking is squelched.

**Comment by smurp** [comment]
* update jQuery to greater than `3.4.0` https://github.com/smurp/huviz/commit/b86ee415c15a980fc7f00812c7c5a4b0448f99f1
* update Express to greater than 
 3.11.0 (to 4.x actually) https://github.com/smurp/huviz/commit/d96781e9d290a7c0ef12946ae5500057aa492333

These updates resolve GitHub's warnings, which won't go away until these changes have been pushed to production.
