### ISSUE TITLE
Alpha displaying oddly

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#266]
I was using alpha over the weekend and couldn't get the commands window to display properly. It looks like it is stuck a step from completion:

![image](https://user-images.githubusercontent.com/11494469/54607930-f7042480-4a25-11e9-872c-b2b828971a26.png)

## Steps to Reproduce (for bugs)

1. Go to Alpha (in Chrome)
2. Load any dataset
3. Hit load
4. You'll see that it just returns the entire Command Window as a long list instead of a series of buttons, etc. 

@antimony27

**Comment by smurp** [comment]
Wolf and I are well aware of this one!  :-)   We are working on it.  Sorry for the temporary disruption of beauty.....

Should we push a slightly earlier version of alpha to beta, so you have something as fresh as possible over there?

**Comment by SusanBrown** [comment]
That sounds like it would be a good idea, if you can confidently push a more current version to beta.
________________________________

**Comment by smurp** [comment]
OK, so I've pushed a fairly recent version of alpha into beta, so beta now has the treats available in alpha before I introduced this bit of unpleasantness.

**Comment by smurp** [comment]
Wolf found my typo!  Alpha is safe again.
