### ISSUE TITLE
"Friendlify" pop up for "next command"

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#27]
- The pop up for a "next command" should be "friendlified" by including the name of the thing. For instance, when the curser hovers over a node on the shelf, instead of the word "select" it should say "select 'Margaret Atwood."
- Likewise, in the History, instead of saying "select settlement" it should say "select settlement Toronto."

**Comment by smurp** [comment]
The call for this is addressed more powerfully by #36. Furthermore, there are also technical limitations on the amount of data which can be presented in the little pointer bubbles, so if we were to do this we'd have to switch back to a technology for the pointer bubbles which was unacceptably slow for this compute-intensive situation.

**Comment by cmiya** [comment]
I agree. It's not necessary. What are your feelings on #34?
