### ISSUE TITLE
why are shorter sparql search terms faster?

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#272]
The first thing to do here would be to make sure that it is NOT the server which is exhibiting this behaviour.  In other words, if it IS the server which is faster with shorter terms then of course there is nothing for us to solve in the HuViz code.

**Comment by antimony27** [comment]
I can never get a sparql search in HuViz to work unless I'm using 3 characters. Anything below that doesn't trigger the search, anything longer fails to load.

**Comment by smurp** [comment]
I believe this issue has been addressed.  Agreed?
