### ISSUE TITLE
make the edge inspector work again

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#275]

**Comment by smurp** [comment]
This might have been broken by the *re-entrancy* work we did to stop using generic (as opposed to unique) id-based selectors.

**Comment by smurp** [comment]
Take a look at how the window for the node inspector is being built now.  If it is relevant to this issue, it might be time to make sure the edge inspector is using that window-building technique now.  That would bring the node inspector, the edge inspector and the instructions for geonames into sync in how they are building their windows.

**Comment by SusanBrown** [comment]
It would be very good to have it back! I don't think we can push beta to prod until it is fixed (and it would be very nice to do so, because the settings are SO much nicer now!) since it is still available in alpha.

**Comment by SusanBrown** [comment]
Can we have an update on where things stand with this? Is it connected to something else that is being worked on (beyond the general connectivity of things) or connected to something that we're waiting on? It occurs to me, anxious as I am to get it, that it would be really great to have it show the source edges/links provided by the Web Annotation data.

**Comment by smurp** [comment]
@SusanBrown @antimony27 This is working well – I'd say – using the new window style established by the node inspector.

**Comment by antimony27** [comment]
Yes! Looks great in alpha Shawn. Thanks!

**Comment by smurp** [comment]
Final touch: hilight an existing inspector if requested again https://github.com/cwrc/HuViz/issues/299
