### ISSUE TITLE
Slippery Nodes/ Default Fisheye Zoom (2.5 hrs)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#28]
PROBLEM:
- Difficulty selecting the desired node--almost seems as if the cursor repels the nodes--so as to drag it in or out of the center of the circle. Especially difficult with large datasets (like the Brontes).

POSSIBLE SOLUTIONS:
- Change the default fisheye zoom and radius to correspond to the size of the dataset.
- Have the cursor act as a bit of a magnet
- Other suggestions??

**Comment by ilovan** [comment]
I lean towards "Change the default fisheye zoom and radius to correspond to the size of the dataset."

**Comment by smurp** [comment]
Another aspect of the challenge sometimes is that the graph can be in motion.  Clicking on a moving node while its position is being modified by a fisheye lens -- with its non-linearity -- is actually a bit harder than spear fishing and not a trivial eye-hand coordination task at all.

**Comment by smurp** [comment]
## Proposal ##

Make the fisheye actually visible as a set of faint, concentric, grey circles -- where the radius of the outer circle shows the radius of the fisheye and the number and spacing of the circles is a function of the amount of magnification.  This might make it clearer where the fisheye is and how its distortion is causing the apparent repelling -- which is purely a result of magnification.

**Comment by cmiya** [comment]
For now, I actually find the fisheye lens okay as it is. Especially when used in combination with the fisheye radius. Changing the default magnification in accordance with the size of the dataset might be a future improvement. But if we build a section on "how to manage large datasets" into the DITA documentation (as I plan to), it should clear things up for the user.

**Comment by jsmithelford** [comment]
agreed.
