### ISSUE TITLE
Provide format for the files to be included in the customized datasets for user testing

### ISSUE THREAD

**Issue by ilovan** [cwrc/HuViz#29]

**Comment by cmiya** [comment]
Related to #31

**Comment by smurp** [comment]
**moved from #31**  presumably now others can do #31

By default `orlandoScrape.py` extracts RDF for all the authors and all the predicates.  This is not normally desired, so restricting the extraction to either a particular set of authors and/or a particular set of predicates is accomplished with the following arguments.

*  `--ids` followed by a comma-delimited set of the writer ids
* `--only_predicate` followed by a comma-delimited set of the predicate ids

Bottom line:  if you provide me with sets of either author ids and/or predicate ids to extract (and a name for the extraction) I can add it to the Makefile which causes them to be built. 

 If either of those sets is tricky then shoot me some email and we can figure out how to automate it.

----

The full set of arguments available to orlandoScrape is documented here:
    https://github.com/smurp/huviz/blob/master/orlandoScrape.py#L514

For reference, this file contains the specifications for the current data sets:
    https://github.com/smurp/huviz/blob/master/Makefile

**Comment by smurp** [comment]
Hopefully this is enough information ot do #31
