### ISSUE TITLE
Load entire graph during Sparql search

### ISSUE THREAD

**Issue by antimony27** [cwrc/HuViz#307]
## Expected Behaviour
Particularly with the addition of LOV, it would be great if users could visualize an entire ontology (against OWL?) without having to search for a term within it.

Unless, of course, it is too large for HuViz to handle.

The SPARQL `LOAD` button should:

* [x] be disabled once the Graph search is started
* [x] AND be enabled if no Graphs are found
* [x] OR be enabled once a Graph is selected
* [x] AND be disabled while term autocomplete is in process
* [x] AND be enabled when the search term is blanked
* [x] AND be enabled when an autocomplete term is selected
* [x] cause the selected term (and its neighbours to the limit indicated) to be loaded
* [x] OR cause the whole dataset (to the limit indicated) to be loaded (if no term is selected)

## Current Behaviour
Currently you have to enter a search time to get results.

**Comment by smurp** [comment]
https://github.com/smurp/huviz/commit/ba7b8177707617a410367b7d1ba25760fb2dea9c
