### ISSUE TITLE
Compile criteria for test datasets in format Shawn needs

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#31]

**Comment by cmiya** [comment]
Related to #29

**Comment by smurp** [comment]
By default `orlandoScrape.py` extracts RDF for all the authors and all the predicates.  This is not normally desired, so restricting the extraction to either a particular set of authors and/or a particular set of predicates is accomplished with the following arguments.

*  `--ids` followed by a comma-delimited set of the writer ids
* `--only_predicate` followed by a comma-delimited set of the predicate ids

Bottom line:  if you provide me with sets of either author ids and/or predicate ids to extract (and a name for the extraction) I can add it to the Makefile which causes them to be built.  If either of those sets is tricky then shoot me some email and we can figure out how to automate it.

----

The full set of arguments available to orlandoScrape is documented here:
    https://github.com/smurp/huviz/blob/master/orlandoScrape.py#L514

For reference, this file contains the specifications for the current data sets:
    https://github.com/smurp/huviz/blob/master/Makefile

**Comment by jsmithelford** [comment]
Need time estimate for how long this will take.

**Comment by smurp** [comment]
I had interpreted this issue as a task for others while I thought the
complementary task for me was #40

On Thu, Oct 1, 2015 at 8:16 AM, jsmithelford <notifications@github.com>
wrote:

> Need time estimate for how long this will take.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/31#issuecomment-144759641>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by SusanBrown** [comment]
Me too.

**Comment by cmiya** [comment]
Me, as well. I think this is something we'll figure it out when @jsmithelford, @kathrynholland and I meet to discuss the test datasets. And then we'll relay the info to Shawn to facilitate #40.

**Comment by cmiya** [comment]
@smurp, what specifically is causing the crashes? Is it dependent on the nodes, edges, predicates or... ?) What is the optimal dataset size we should aim for?

**Comment by cmiya** [comment]
Working doc for test datasets (still in planning phase):
https://docs.google.com/document/d/1ZtAbABN8tbIIfZWlgfktx2-ue_qdnBNA5KxY73fGhpM/edit?usp=sharing

**Comment by cmiya** [comment]
@smurp Is there a way to run a test scrape?

**Comment by cmiya** [comment]
@smurp, we’ve compiled the following list of new datasets (groups of author ids) to build for testing. As mentioned, the browser can only handle datasets of around 600 (or less) edges. It is difficult to predict how large a network will be based on the number of subject-authors. Early Writers, for instance, has 12 subject-authors and 835 edges. Margaret Atwood, by comparison, has one author and 2345 edges. Both are too large. We’ve tried to keep the scope narrow and in some cases, like Newnham College, have created condensed “boutique” versions of the author network.

We also tried to include a variety of historical periods and genres. @SusanBrown, if you have any other suggestions for test datasets (bearing the size restrictions in mind), please let us know and we would be happy to add them.
 
DATASETS to PRESERVE:
*These are current, working datasets we would like to include for testing based on browser performance.
- R. M. Ballantyne
- Maria Abdy
- Brontes
 
PROPOSED DATASETS:
 
Single authors:
- Augusta Ada Byron
  - Author id: byroau

Organizations:
- Newnham College (artificially condensed by way of OVis (Boutique datasets!)
  - Author ids: daviem, butlejo, fordis, fawcmi, brownro, glaska, schrol, shawge
- Académie des Femmes (modernist)
  - Author ids: steige, barnna, loy_mi
- 1917 Club (modernist)
  - Author ids: sharev, macaro, hamima
- Female Anti-Slavery Society (Mid-19th Century American)
  - Author ids: elizhe, martha, fullma
- Nuns: Middle Ages
  - Author ids: hildbi, helo__, marifr
- African National Congress (1960-1991)
  - Author ids: britve, renama, gordna, murpde, slovgi

Periodicals:
- The Yellow Book AND poet
  - Author ids: levyam, watsro, meynal, almala

Publishing Houses
- Dial Press (modernist)
  - Author ids: fordma, moorma, barndj, jessft
- Kelmscott Press (Victorian)
  - Author ids: swanan, wildja, morrwi, gregau

Genres:
- Famous Cookbooks 1750-1850
  - Author ids: cookan, glasha, pluma2, halesa, johnch

**Comment by cmiya** [comment]
@smurp Is there anything else you need? Should I write this as code and insert into the Makefile or leave as is?

**Comment by susanirenebrown** [comment]
Chelsea, was this list based on the google doc outlining desirable datasets that I wrote up ages ago? I know I found it recently and pointed you folks to it as a basis for this work. Could you confirm that you considered those suggestions?

I think the Shakespeare one should be preserved and will be more interesting once we have two-way links.

**Comment by jsmithelford** [comment]
I agree with Susan that shakwi should also be preserved. I think this was just a slight oversight on our part. The dataset loads with no problems. The only concern with it, as with the others, would be the

**Comment by cmiya** [comment]
@SusanBrown, agreed about Shakespeare - sorry about that! The document has been edited to include that dataset. Regarding the previous suggestions, we started off by looking at the google doc on desirable datasets, but quickly realized that most of the sets would be too large for the tool to handle without crashing. We had to choose groups that were limited to 600 or less edges.

**Comment by SusanBrown** [comment]
Got it. That’s what I figured but I wanted to check.

**Comment by cmiya** [comment]
@smurp The Dataset list has been updated to include: Tait's Edinburgh Magazine, Englishwoman's Review, Minerva Press, The Victoria Press and 17th Century Quakers. Once they've been tested, let me know if any of the datasets are too large and need to be pared down by making the author ids list shorter.

**Comment by smurp** [comment]
Can you point me to the latest dataset?

On Sun, Dec 13, 2015 at 5:17 PM, cmiya <notifications@github.com> wrote:

> @smurp <https://github.com/smurp> The Dataset list has been updated to
> include: Tait's Edinburgh Magazine, Englishwoman's Review, Minerva Press,
> The Victoria Press and 17th Century Quakers. Once they've been tested, let
> me know if any of the datasets are too large and need to be pared down by
> making the author ids list shorter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/31#issuecomment-164313679>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by symulation** [comment]
Likely time to have Jeff pull another one.


Jeff, would you be able to pull a new version of the Orlando data using the “One Author Per Line” format you gave me earlier and then share it with Shawn?  Likely share it with Rob too?


  -John

John Simpson Ph.D. 

Digital Humanities Specialist 
Spécialiste des Humanités Numériques

john.simpson@computecanada.ca
 
(t) 780.248.5872
(f) 778.782.3592 

36 York Mills Road, Suite/Unité 505, Toronto, Ontario, Canada M2P 2E9 
www.computecanada.ca
 / www.calculcanada.ca
 
@ComputeCanada

**Comment by symulation** [comment]
If you have it, I'll consume it. No worries otherwise. -rhw

**Comment by SusanBrown** [comment]
Unless I am mistaken, Jeff just pulled a full set of the currently published Orlando data and the bible entries a week or two ago for Rob.
