### ISSUE TITLE
Refresh doesn't wipe the history tab (30 min)

### ISSUE THREAD

**Issue by jsmithelford** [cwrc/HuViz#32]

**Comment by ilovan** [comment]
related to #26

**Comment by jsmithelford** [comment]
related to Issue #26

**Comment by jsmithelford** [comment]
Also related to issue #8

**Comment by smurp** [comment]
The Reset button has been disabled and probably won't come back in its current form given that the goal is to move toward a more dynamic, nStore-based approach. Hence the milestone is: "In the Fullness of Time"
