### ISSUE TITLE
Current Command should not have blanks, instead replace with options (4 hrs)

### ISSUE THREAD

**Issue by jsmithelford** [cwrc/HuViz#33]
![screen shot 2015-09-24 at 1 33 32 pm](https://cloud.githubusercontent.com/assets/5768416/10084540/3b9c51bc-62c1-11e5-955f-8247c27cc396.png)

Instead of two blanks, have greyed out VERB in the first; have greyed out SET/CLASS in the second. When you've done it, it fills in to show what the user has done.

**Comment by smurp** [comment]
closed by
* https://github.com/smurp/huviz/commit/d0d55ae893a2c10659ff189f855029030b330bee
* https://github.com/smurp/huviz/commit/6927bd143b497609e37564b3227d1fd15107a18e
