### ISSUE TITLE
Continuously update the current command preview, displaying auto-verb and target node (3 to 7 hrs)

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#36]
Currently users aren't ever able to see either the command that is about to be executed, the command which was just executed or any of the commands which had been executed earlier.

Earlier, before _immediate execution mode_ (where-in commands are executed the instant that there are no more blanks in it) the command about to be executed was visible in the current command box and didn't get executed until the user pressed the "Do-it" button.  Now in _immediate execution mode_ the command to be executed disappears the instant that the command has been completed by a click, because the last blank filled gets set back to empty.

The suggestion here (which was really part of the design of _immediate execution mode_) is that whenever the mouse is hovering over something and either the verb or the _object phrase_ (or both) will be resolved to something with a click, then the verb and/or object which will be activated upon a click ought to be displayed with some special formatting in the current command box.  The special formatting (italics?) will specially hilight the portions of the command which are not yet fixed, but which will be upon a click.

I suggest a _high priority_ and _before user testing_ because I think this will considerably improve users' understanding of what is going on and what is about to happen.

* [x] update Current Command when hovering over a node and there is no SET/SELECTION
* [x] update Current Command when hovering over a verb
* [x] update Current Command when hovering over a SET when no set is engaged
* [x] update Current Command when hovering over class when none is engaged
* [x] include the predicate in the updated Current Command when hovering over a predicate!
* [x] when there are any Selected nodes then the Current Command should show `____ Selected .`
* [x] suppress Commands entering the History like `Draw the Selected set regarding SUBPROPERTIES-OF-WHATEVER` when collapsed Predicate WHATEVER is clicked
* [x] ensure `Draw the Selected set regarding every WHATEVER` is pushed into the Command History

**Comment by jsmithelford** [comment]
Related to #33

**Comment by cmiya** [comment]
Will wait until feedback from user testing.

**Comment by smurp** [comment]
I really think delaying this is a mistake.  It means that nowhere is the
user shown what is going to happen if they click.  Babies, bathwater.

On Thu, Oct 1, 2015 at 9:16 AM, cmiya <notifications@github.com> wrote:

> Will wait until feedback from user testing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/36#issuecomment-144776278>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by SusanBrown** [comment]
I will leave it for others who thought that we could do without it to respond. I agree that there should be some indication, somehow, of what will happen if a user clicks. I thought people were saying that we would have that in another way. Hopefully someone can reconstruct the logic of the decision.

**Comment by smurp** [comment]
The alternative place for displaying the full command that has been
mentioned is right in the little yellow tooltip and I'd suggest that would
make for a rather large gizmo obscuring visibility of the action under the
cursor.  Another factor is that the yellow tooltip is using some intense
performance trickery (rendering text to an image which is dynamically
swapped into use as the cursor image) which has limits on the size of the
image which can be used.  Putting more in there would risk bugs with
clipping of the viewable region of the tooltip.

On Thu, Oct 1, 2015 at 2:50 PM, SusanBrown <notifications@github.com> wrote:

> I will leave it for others who thought that we could do without it to
> respond. I agree that there should be some indication, somehow, of what
> will happen if a user clicks. I thought people were saying that we would
> have that in another way. Hopefully someone can reconstruct the logic of
> the decision.
>
> > On Oct 1, 2015, at 4:52 PM, Shawn Murphy <notifications@github.com>
> wrote:
> >
> > I really think delaying this is a mistake. It means that nowhere is the
> > user shown what is going to happen if they click. Babies, bathwater.
> >
> > On Thu, Oct 1, 2015 at 9:16 AM, cmiya <notifications@github.com> wrote:
> >
> > > Will wait until feedback from user testing.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cwrc/HuViz/issues/36#issuecomment-144776278>.
> > >
> >
> >
> >
> > --
> > Shawn Murphy
> > smurp@smurp.com
> > (780) 903-2428
> > http://www.smurp.com
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/cwrc/HuViz/issues/36#issuecomment-144844705>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/36#issuecomment-144859879>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by cmiya** [comment]
Okay, if it's only 2 more hours with a much higher value for time then it makes sense as you said to keep it as a milestone issue.

@jsmithelford and @ilovan, any thoughts on this? Are we agreed to keep it as a milestone?

**Comment by jsmithelford** [comment]
The logic was behind this decision was: 1) we didn't know how much time this would take, and feared it may take too much time (time we didn't have before testing) and 2) that we felt that we might be able to get feedback from users to indicate whether this was necessary or not--that is, we felt that testing might reveal the things that need to change with functionality better than our anticipation of it. Having said that, I am fine with reversing this decision given the time estimate if everyone else agrees.

**Comment by smurp** [comment]
I've pulled a small usability issue out into #241
