### ISSUE TITLE
nodes must be able to have the same name

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#360]
Nodes which have the same name but which have different urls should be treated as different things.

## Expected Behaviour

Here are some things which have the same name, but which are different.

The [Jewish Novelist Biographies](https://raw.githubusercontent.com/cwrc/testData/master/sparqlOutputs/jewish_novelist_biographies.ttl) contains these things which have the same name, but are different things:

The name **Aguilar, Grace - PhysicalHealth Event** is shared by these things:
* http://cwrc.ca/cwrcdata/aguigr_PhysicalHealth_Event1
* http://cwrc.ca/cwrcdata/aguigr_PhysicalHealth_Event2
* http://cwrc.ca/cwrcdata/aguigr_PhysicalHealth_Event3

The name **Levy, Amy - Spatial (travelsTo) Event** is shared by multiple nodes.

The name **Levy, Amy - InstitutionalEducation Event** is shared by multiple nodes.

There are others.

The [Unitarian novelist biographies](https://raw.githubusercontent.com/cwrc/testData/master/sparqlOutputs/unitarian_novelist_biographies.ttl) contain many things which share names with other things, such as:

The name **Naigara Falls** is shared among these things:
* (Canada) https://www.geonames.org/6087892/niagara-falls.html
* (USA) https://www.geonames.org/5128723/niagara-falls.html

## Previous Behaviour
There were a large number of unpleasant results of these collisions.

http://alpha.huviz.dev.nooron.com/#load+https://raw.githubusercontent.com/cwrc/testData/master/sparqlOutputs/jewish_novelist_biographies.ttl+with+http://sparql.cwrc.ca/ontology/cwrc.ttl

* notice that `All (255)` does not equal `Shelved (236)`
* `Activate All` is very confused, not graphing everything.
* Set membership count errors
* Shelf in wrong sort order
* Nodes sticking on the shelf

http://alpha.huviz.dev.nooron.com/#load+https://raw.githubusercontent.com/cwrc/testData/master/sparqlOutputs/unitarian_novelist_biographies.ttl+with+http://sparql.cwrc.ca/ontology/cwrc.ttl

##  Once this enhancement was made it solved these bugs

#354 #359 #356 #357

## To see this working in a very simple way

http://alpha.huviz.dev.nooron.com/#load+/data/name_lookup_demo.ttl+with+/data/owl_mini.ttl

1. engage `Activate`
1. engage `Label`
1. click `All`

Notice that there are two `Mitte` geonames nodes.  One in `Berlin` and one in `Bielefeld`.

![image](https://user-images.githubusercontent.com/774119/73042106-37aba600-3e60-11ea-8278-c58bb7226ef8.png)

**Comment by smurp** [comment]
@SusanBrown @antimony27 This was the key to a whole bunch of trouble.  I've added this the **User Testing / Documentation** tab in ZenHub.

**Comment by SusanBrown** [comment]
This (nodes with same names but different URIs) will happen inevitably so it’s good that you've identified this as the source of the counting problem etc.

On Jan 23, 2020, at 8:19 PM, Shawn Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


@SusanBrown<https://github.com/SusanBrown> @antimony27<https://github.com/antimony27> This was the key to a whole bunch of trouble. I've added this the User Testing / Documentation tab in ZenHub.
