### ISSUE TITLE
revise wording of popup for shareable link

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#363]
Shareable link from HuViz (alpha.....):
![image](https://user-images.githubusercontent.com/545952/73050668-d4108100-3e3d-11ea-8768-a00595de459e.png)

**Comment by smurp** [comment]
The functionality is improved with this commit https://github.com/smurp/huviz/commit/85f2acf and Wolf is on making this prettier.  I'd say we should push this to beta even as it is.

**Comment by smurp** [comment]
It has been cosmetically improved
![image](https://user-images.githubusercontent.com/774119/73123728-49da3100-3f93-11ea-9a5c-f963412fc12e.png)

@SusanBrown Further wording changes required?
