### ISSUE TITLE
Serious typo on Intro screen

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#364]
Um...I would swear that Woolf was spelled properly before, but it is not and the modernists in the room will be very unhappy to see that we left out an "o". 

Could this be fixed asap? Demoing at about 10 or 11 Mtn time Saturday.

it reads now: 
Virginia Wolf hasGender woman
Virginia Wolf hasSister Vanessa Bell
Virginia Wolf inhabits London

Woolf has two o's

**Comment by smurp** [comment]
@SusanBrown Which version are you using?  Beta? Alpha? Production?

**Comment by smurp** [comment]
Fix deployed alpha, beta, master and cwrc.  

@SusanBrown (Still useful to know which version you're having people use, so we can step with extra care around it.)
