### ISSUE TITLE
Abstract the Terminology Set (4 hrs)

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#39]
## Proposal: ##

We could facilitate A/B testing of different sets of terms by adding an entry to the `Setting` tab which is a select box offering various canned sets of verb names.  These could be maintained in an external data structure (a .json file for example) which could be easily added to by non-developers.

This work would require abstracting all of the verb and set names so that their presentation to users would always be in the configured vocabulary.

This would, of course, also address the concern in #19 by providing a way to actually experiment with different terminology sets.  

## Steps (4 hrs) ##
* [x] abstract all `verb` names internally, so their presentation to users can be configured
* [x] abstract all `set` names internally, so their presentation can be configured
* [x] embed the human_terms in a single, replaceable, object

## Optional Steps (5 hrs) ##
* [ ] add a configuration entry **Terminology Set** (or similar) which offered access to sets defined in an external .json file
* [x] also affect any uses of the terms in the hover text
* [ ] and quick reference

## Supercedes Issues ##
* #19 
* #20

**Comment by ilovan** [comment]
I think being able to do that is a great idea but I am wondering if we will be able to get truly representative results with the relatively small expected number of testers.

**Comment by ilovan** [comment]
Decision: 
We are leaving this for after user testing, if we find it's something users need.

**Comment by smurp** [comment]
closed by https://github.com/smurp/huviz/commit/d875ab416bce899c65dce566ad48f4ee0da7851a

**Comment by smurp** [comment]
finally actually replace 'Choose/Unchoose/Chosen' with 'Activate/Deactivate/Deactivated'
* https://github.com/smurp/huviz/commit/c8b40afaea486681a3cb5c0aac1e0e93e7da3075
* https://github.com/smurp/huviz/commit/77d926e374f60937e1d43042300d6d3896b1b5d5
