### ISSUE TITLE
Generate the datasets requested for User Testing (6 hrs)

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#40]
* [ ] Encode in the Makefile the various datasets requested for User Testing.  
* [ ] Run the extractions and add them to the repo.  
* [ ] Test for size, loadability and correctness.
* [ ] Summarize the stats in the select box.
* [ ] Communicate for testing and feedback.
* [ ] Rinse and repeat to refine as requested.

**Comment by cmiya** [comment]
Just going through the datasets now - noticed that the Hover Bubble for the datasets pulldown menu reads "datasets are in order of increasing complexity." As far as I can tell they are ordered not by complexity (which I think is meant to refer to the number of nodes/edges?), but alphabetically.

Another quirk I noticed is that the nodes themselves are arranged alphabetically according to the node name - but backwards/counterclockwise! Not a huge deal, just something I found a bit curious.

**Comment by smurp** [comment]
Actually aren't they ordered alphabetically with "The " being ignored?  The
ones like "17th" and "1917" as the first significant words I've lumped at
the end of that group.

I guess there are enough of them now that we should ask ourselves how they
ought to be ordered.  I sorted them alphabetically to facilitate people
familiar with the list finding what they are looking for but an argument
could certainly be made for file-size, node-count or edge-count being used
as proxies for complexity and order on one of those factors.  Then, of
course, I should bring the "in order of increasing complexity" docs to be
brought into line with the implemented reality.

Thoughts everyone?

On Fri, Jan 15, 2016 at 2:48 PM, cmiya <notifications@github.com> wrote:

> Just going through the datasets now - noticed that the Hover Bubble for
> the datasets pulldown menu reads "datasets are in order of increasing
> complexity." As far as I can tell they are ordered not by complexity (which
> I think is meant to refer to the number of nodes/edges?), but
> alphabetically.
>
> Another quirk I noticed is that the nodes themselves are arranged
> alphabetically according to the node name - but backwards/counterclockwise!
> Not a huge deal, just something I found a bit curious.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/40#issuecomment-172103881>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by cmiya** [comment]
The datasets, as a whole, seem to be loading much faster. The Bronte Sisters and Early Writers, for instance, work fine now.

Of the new datasets, here are the ones that are causing crashes:

### Organizations:
Academie des Femmes
African National Congress ** *I think there is a typo in the name ("Congress" not "Contgres")*
Newnham College
1917 Club
17th Century Quakers

### Periodical House:
Tait's Edingburgh Magazine
Yellow Book AND Poet

### Periodicals:
Dial Press
Kelmscott Press
Minerva Press
Victoria Press

**Comment by cmiya** [comment]
##### Three things... 

1. Shawn, I believe we decided to "grey out" the non-functional datasets, as a way to indicate to users that they are currently broken. *Hows is that coming??*

2. I also noticed that about half of the datasets are still missing attributes in the hover-bubble (nodes, edges, predicates). *Were you able to automate the generation of this info or is it being down manually? Will this be ready for the demo version?

3. Will the public version of the tool be ready for the demo on Tuesday? I'm just want to make sure because I'll be printing the URL on the handouts. And just to double-check... Is [this] (http://huviz.dev.nooron.com/) the right address for the demo site?

**Comment by cmiya** [comment]
I should also say, I really like the new and improved formatting! The new pull-down menus, colour scheme, etc. all look fantastic.

**Comment by smurp** [comment]
1 and 3 will be done right away (within the hour).  2 should probably come
after the specified issues.

On Sun, Jan 17, 2016 at 10:58 PM, cmiya <notifications@github.com> wrote:

> Three things...
>
>    1.
>
>    Shawn, I believe we decided to "grey out" the non-functional datasets,
>    as a way to indicate to users that they are currently broken. *Hows is
>    that coming??*
>    2.
>
>    I also noticed that about half of the datasets are still missing
>    attributes in the hover-bubble (nodes, edges, predicates). *Were you able
>    to automate the generation of this info or is it being down manually? Will
>    this be ready for the demo version?
>    3.
>
>    Will the public version of the tool be ready for the demo on Tuesday?
>    I'm just want to make sure because I'll be printing the URL on the
>    handouts. And just to double-check... Is this
>    <http://huviz.dev.nooron.com/> the right address for the demo site?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/40#issuecomment-172433073>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by smurp** [comment]
The changes to the menu are visible at:
  http://huviz.dev.nooron.com/

and the beta
  http://beta.huviz.dev.nooron.com/


On Sun, Jan 17, 2016 at 10:47 PM, cmiya <notifications@github.com> wrote:

> The datasets, as a whole, seem to be loading much faster. The Bronte
> Sisters and Early Writers, for instance, work fine now.
>
> Of the new datasets, here are the ones that are causing crashes:
> Organizations:
>
> Academie des Femmes
> African National Congress ** *I think there is a typo in the name
> ("Congress" not "Contgres")*
> Newnham College
> 1917 Club
> 17th Century Quakers
> Periodical House:
>
> Tait's Edingburgh Magazine
> Yellow Book AND Poet
> Periodicals:
>
> Dial Press
> Kelmscott Press
> Minerva Press
> Victoria Press
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/40#issuecomment-172431954>.
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com
