### ISSUE TITLE
finish XPath version of HuViz orlandoScrape (3 to 8 hrs)

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#41]
Shawn (maybe working with John) should finish merging their two versions of orlandoScrape, the XPath version and the HuViz version.

**Comment by ilovan** [comment]
Not sure if this is the best place to do so or not, but if @smurp and @symulation could agree on a timeline to work on this issue once the contract paperwork is finalized (we're aiming for the end of this week), then that would be great.

**Comment by smurp** [comment]
The code as it stands appears to be producing satisfactory output.
