### ISSUE TITLE
point HuViz at the latest Orlando Ontology as hosted on GitHub (3 hrs)

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#42]
Have users of HuViz get their version of the ontology from the appropriate GitHub repo directly.  The file needs to be in .ttl format for HuViz to be able to parse it.  Communicate with Rob requesting a parallel version being included in the repo.

**Comment by cmiya** [comment]
@smurp Retrieving their version of the ontology seems to refer to a feature that would allow users to upload their own ontology. But aren't we waiting to implement this until after testing?

**Comment by cmiya** [comment]
@smurp Do you mean the HuViz repository? (https://github.com/cwrc/HuViz) According to @ilovan, you should be able to grab it from either http://cwrc.ca/ontologies/ or http://cwrc.ca/ns/.

**Comment by SusanBrown** [comment]
I think there’s some confusion here. Yes, we are indeed leaving allowing users to upload their own ontology until after testing. I believe that this ticket refers to using/pointing to the latest version of the Orlando ontology.

**Comment by cmiya** [comment]
@smurp Instead of creating a duplicate could we just use the one in the Schema directory? Also, if the first half of the description is related to the custom sets, we could move this into #12.

**Comment by smurp** [comment]
Excellent.  I'll update the code to either load the ontology from http://cwrc.ca/ontologies/OrlandoOntology-2015-11-16.ttl or from a copy of that ontology which is loaded into the huviz repo.  (A copy might be necessary if the web server it is hosted on does not have a CORS configuration which permits  access from within huviz.)

https://en.wikipedia.org/wiki/Cross-origin_resource_sharing
