### ISSUE TITLE
Write Script for User Tests (0 hrs)

### ISSUE THREAD

**Issue by jsmithelford** [cwrc/HuViz#46]

**Comment by smurp** [comment]
@jsmithelford Could you expand on your intention?  

Have you seen http://alpha.orlando.dev.semandra.com/tests ?

Do you mean that the other issues (to the extent that it is useful) should have tests added to this suite?  If that is a requirement then that would probably add about a third to the quote.  If often takes the addition of special instrumentation to make things properly testable.

**Comment by smurp** [comment]
In recent work, where it is the case that there is an intense piece of behaviour which requires automated testing to protect it from future damage I've been making sure there are tests.  Very little of the work we've outlined in this milestone is of that character -- but some is and those tests are relatively simple ones -- so I've been keeping in mind the need to include those tests for the 2 or 3 issues in that category.

So, barring very specific new tests you've got in mind that are not variations on things already tested, it could be there is little to worry about WRT tests in this milestone...  So I'll estimate (0 hrs) unless we come up with some new specifics.

**Comment by jsmithelford** [comment]
Ooops, sorry Shawn, this is not your assignment, and has nothing to do with code. Apologies for the confusion. This is an assignment for Chelsea and I (and others) to write a literary script for the user testing, to direct users so that we can get feedback for the particular issues that we need addressed.

**Comment by smurp** [comment]
Ha ha!  That's funny. I'm an old dog who remembers that "end-user tests" used to be the name (in Extreme Programming, the grandparent of Agile) for what we now call https://en.wikipedia.org/wiki/Acceptance_testing

**Comment by cmiya** [comment]
haha that's correct - it's an actual script, not a programming reference. Sorry for the confusion Shawn!
