### ISSUE TITLE
Situate the huviz codebase under github/cwrc (3 to 5 hrs)

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#47]
## discovery phase ##
* [ ] figure out how to do a pull request from an existing codebase https://github.com/smurp/huviz/ into another which did not start off as a clone
* [ ] OR figure out how to move the issues from https://github.com/cwrc/HuViz into a newly-made clone of https://github.com/smurp/huviz/
* [ ] OR an alternative?

## execution phase ##
* [ ] triage and merge the existing branches
* [ ] do whatever was figured out in the discovery phase

**Comment by ilovan** [comment]
@jefferya , do you have any suggestions for what would be the best way to proceed?
thanks

**Comment by cmiya** [comment]
@smurp Any updates on this?

**Comment by smurp** [comment]
closed with a12a17aab930ea992ef3826ec2332a801e834278 being pushed to https://github.com/cwrc/HuViz/
