### ISSUE TITLE
Replace Nooron Logo with CWRC Logo in browser tab label

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#52]
Replace Nooron Logo with CWRC Logo in browser tab label for public test site (http://huviz.dev.nooron.com/).

@ilovan is going to provide a link to the logo file.

**If could have done before demo tomorrow that would be great.

**Comment by ilovan** [comment]
Here are the accepted variants: https://drive.google.com/folderview?id=0B4CtWuyM04e4floyaGJzX0dtd3F2cFV6RnhnUWxzaW9KMGZmTDlnZ3EwaVFSVnZKSkJoelE&usp=sharing
Take your pick.

**Comment by smurp** [comment]
Is there a website which displays the "browser tab label" ie the ".ico" file?

**Comment by smurp** [comment]
If there were an example of an .ico file on an existing site then I wouldn't have to make one -- which because of the size of them can be slightly tricky.

**Comment by smurp** [comment]
I ended up going with this one:
  https://ssl.gstatic.com/docs/doclist/images/icon_11_image_xl128.png
for best results at the small size in a tab.

**Comment by smurp** [comment]
closed with https://github.com/smurp/huviz/commit/10ab25eab7174960ccd550c00a0ed78f34dddc30

**Comment by SusanBrown** [comment]
Sorry: Have send email with more appropriate icon. Apologies.

**Comment by smurp** [comment]
For clarity, the nooron logo was being inherited from nooron.com rather than actually being a part of the current huviz repo.
