### ISSUE TITLE
Snippets: Cambridge Attributes

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#57]
How should we emphasize the connection to Cambridge Press? Is there a way to point users back to the original article? As mentioned, this is important both for practical research purposes and copyright.

Using actual hyperlinks would be useful as a way to integrate the tool into the existing Orlando site, but will be problematic if the user doesn't have a subscription.

**Comment by cmiya** [comment]
@smurp and @SusanBrown would love to hear your input on this.

**Comment by smurp** [comment]
(The closing was an bogus artifact of the performance of #47)

**Comment by smurp** [comment]
<img width="316" alt="link_to_cambridge" src="https://cloud.githubusercontent.com/assets/774119/13480595/0d0fc6a4-e09c-11e5-9211-7d4fa33765c7.png">

@cmiya Is this essentially a formatting question?  Admittedly the existing links to the original Cambridge articles are not super prominent -- being indicated only by the underscore under the author name in the snippet windows. So acknowledging that there *is* such a link are we talking about how to make it more visible or known to users?

There seem to be a couple of approaches:

* make it more prominent, ie make the text blue and leave it underlined to make it look like a typical hypertext link
* precede it with the font-awesome "external link" icon
![fa-external-link](https://cloud.githubusercontent.com/assets/774119/13480824/bad92996-e09d-11e5-8701-b1086a30df73.png)

* or precede it with the font-awesome "link" icon
![fa-link](https://cloud.githubusercontent.com/assets/774119/13480829/c441cc18-e09d-11e5-93e5-39651810e4fa.png)

* and/or document somewhere the fact that links to full Cambridge texts are available in the snippet windows

**Comment by SusanBrown** [comment]
If I can weigh in, I would say it’s about making it more prominent: blue, underlined, bold, plus external link icon.

**Comment by smurp** [comment]
Done, done, done, done, done and added the hover text "see full text at Cambridge".

Closed with 5aba9e9 and released to production, beta and alpha

**Comment by smurp** [comment]
removed obnoxious alert during snippet display 4dd73fe
