### ISSUE TITLE
make the Commands tab window taller and/or resizable

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#61]
## Problem

When the `Commands` tab is selected the window is not as tall as it could be and that makes the **Edges of the Selected Nodes** picker quite challenging to use.
## Alternatives:
1. make the dialog as tall as it can be (while still showing the **Discard Bin**)
2. make the dialog resizable

**Comment by smurp** [comment]
see #21

**Comment by antimony27** [comment]
This issue has been taken over by #104
