### ISSUE TITLE
Remove "Reset"; make so Help Window doesn't automatically open up (only after clicking on Tab)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#62]
In the pre-testing (test of the survey), we found that the "Reset" help box gets confused with the actual Reset button. The Help window also distracts from the assigned task structure of the survey.

Proposed Solution (for purposes of testing):

- Remove "Reset" explanation from Commands Tab; instead include in the Help Window
- Stop the Help Window from opening automatically; instead it will open when clicked

**Comment by cmiya** [comment]
@smurp If it's not too much trouble - could you complete this for testing?

**Comment by smurp** [comment]
Could you clarify a couple of points about this for me?

1. By saying "for purposes of testing" are you saying that you want these behaviours preserved but disabled for the purposes of testing, ie turned off by a switch which can be toggled back on for deployment?
1. Are you saying you want just the "Reset" explanation moved to the help window or are you asking for second yellow hint -- the "Two Ways to Execute Commands" explanation -- moved to help too?

**Comment by cmiya** [comment]
1. A toggle on-off switch would be really useful. How easy would that be to achieve?
2. Move both.
3. A third request, could you include a link to the full documentation in the Help Window (http://cwrc.ca/HuViz_Documentation/)? I'm not sure about placement - perhaps at the very top? What do you think?

**Comment by smurp** [comment]
Toggle in the settings?  Top sounds good.

On Wed, Mar 23, 2016 at 5:23 PM, cmiya <notifications@github.com> wrote:

>
>    1. A toggle on-off switch would be really useful. How easy would that
>    be to achieve?
>    2. Move both.
>    3. A third request, could you include a link to the full documentation
>    in the Help Window (http://cwrc.ca/HuViz_Documentation/)? I'm not sure
>    about placement - perhaps at the very top? What do you think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/62#issuecomment-200580872>
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by cmiya** [comment]
@smurp As agreed in the meeting today, we can just comment out for now.

**Comment by smurp** [comment]
closed by 9d55e95 b888b9e e2594bc 4b3c003
