### ISSUE TITLE
Change "Like" bar Terminology

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#64]
### Problem:
- Testers frequently commented that the "Like" bar reminded them of Facebook/social media
### Solution:
- Change to "Search" next to bar
- Keep as "Like" in the Commands Tab?? Displaying: `All search 'Duchess'`, for instance, doesn't work grammatically and may cause more confusion

**Comment by smurp** [comment]
In the _command language_  context ``like`` works nicely.  The word was intended to make sense in  situations like :

* ``Activate all Person like 'Byron'.``
* ``Label Organization like 'Church'.``

Perhaps ``matching`` would make more sense as a field label while also working in the _command language_ context.

**Comment by SusanBrown** [comment]
what does “like” do? Is it an exact or a fuzzy match?

**Comment by antimony27** [comment]
@smurp Create  hover for "like" that describes: A string will be matched against the labels of entities, with regex potential.
Change "Like" to 'Match"

**Comment by smurp** [comment]
So we've decided to change the term "like" to the term "matching".  This will result in commands like:

* `Activate all Person matching 'Byron'.`
* `Label Organization like 'Church'.`

Of course the form element should be changed to read "matching".

**Comment by SusanBrown** [comment]
Yes, matching works better than match (even if it spoils Kim’s matchbox pun).

On May 11, 2018, at 10:42 AM, Shawn Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


So we've decided to change the term "like" to the term "matching". This will result in commands like:

  *   Activate all Person matching 'Byron'.
  *   Label Organization like 'Church'.

Of course the form element should be changed to read "matching".

**Comment by smurp** [comment]
https://github.com/smurp/huviz/commit/982a74bd8df3e6eb79916abc58717dc474e13274

`like` changed to `matching` in the UI
