### ISSUE TITLE
Fix display issue with special characters

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#65]
### Fix display issue caused by special characters (see esp. Bronte dataset).

![screenshot of display issue]
(http://beta.cwrc.ca/islandora/object/cwrc%3Af4f2b0b4-46c5-4a2d-94d9-134c093b738b/datastream/OBJ/view)

**Comment by smurp** [comment]
fixed by 46168c21ddd4db327a3db8f29588e18e3fb4014e
