### ISSUE TITLE
Add Credits/"About" Tab

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#66]
- [x] Create an About Tab
- [ ] Add credit list to About Tab (*Chelsea will circulate a GoogleDoc to contributors to add themselves to)
- [x] Add link to[ Documentation](http://cwrc.ca/HuViz_Documentation/)
- [x] Make the tabs https://jqueryui.com/tabs/#collapsible to cope with removal of the `___` tab

**Comment by cmiya** [comment]
**QUESTIONS:**

- We already have an "Info" Tab. Will the info in the "About" Tab be much different? Should we combine the two?

- Should the link to Documentation be in the About Tab or the Help Tab? (*guessing the later)

**Comment by smurp** [comment]
I think the new tab should be called "Credits" while the "Info" tab should continue to show "front page" content.  I've put the doc link in the help tab.

**Comment by smurp** [comment]
Credit tab ready for content after commit db23e57

**Comment by cmiya** [comment]
Thanks Shawn! Looking at it now. Can you still minimize it without the button?

**Comment by cmiya** [comment]
If the top bar is getting too crowded, I would suggest drop-down menus. Change "Intro" Tab to "About" Tab with the drop down options "Intro" and "Credits." The "Help" Tab should also have the drop down options "Quick Start" and "Complete Manual." Then you would still have room for the minimize button at the end and there would be no need to stretch out the window and change the layout. That would be my suggestion.

**Comment by ilovan** [comment]
I agree with @cmiya . 
So, just to recap, we would still have four tabs, two of them with drop-down menus:

About

- Intro
- Credits

Settings
Commands
Help

- Quick start
- Complete Manual



@smurp , do you think this is something you could implement prior to user testing?

**Comment by smurp** [comment]
An advantage of having the "Quick Start" in its own little window is that one can refer to it while following along in the "Commands" tab so perhaps isn't well suited to display among the tabs.

Likewise the "Huviz Documentation" (which is really great by the way!) would be cumbersome in a tab because it has a lot of internal structure (pages, links, etc) as well as including some large graphics:

![a large image](http://beta.cwrc.ca/islandora/object/cwrc%3A44a189be-7705-4a97-814d-bf1891fab375/datastream/OBJ/view)

Given these problems with the "Help" tab (neither sub section fitting well) I'd suggest the current situation is actually preferable.

**Comment by SusanBrown** [comment]
Agree that quick start is best kept separate from the command tab so they can both be accessed at once.
Quick start box needs to be taller.
Typo: that have beeen dragging into the centre. —> that have beeen dragged into the centre.
Help then doesn’t logically belong as a tab in the top right.Perhaps there should be a clickable question mark on the far right of the tabs (there is blank space there now).
I am not sure that Help is best on totally separate screens—I had thought it could be two other tabs on the same popup pane as the Quick Start, but I think that is what we’re doing with other CWRC interfaces so let’s try it for now.

**Comment by smurp** [comment]
* quick start box now 40% of window height rather than 24%
* beeen --> been
* Help is now the rightmost tab labelled with a question mark (changing it
from a tab to a "different thing from a tab but beside the tabs" would be a
fairly tricky job... 3hrs?)

Could you clarify the final request about the manual?  Are you saying that
you'd like the "Help" dialog box --  which currently comes up when you
click the Help (now question-mark) tab -- to itself have two tabs: "Quick
Start" and "Documentation" and for the current HuViz Documentation to
appear in that second tab? ie http://cwrc.ca/HuViz_Documentation



On Fri, May 6, 2016 at 7:58 PM, SusanBrown <notifications@github.com> wrote:

> Agree that quick start is best kept separate from the command tab so they
> can both be accessed at once.
> Quick start box needs to be taller.
> Typo: that have beeen dragging into the centre. —> that have beeen dragged
> into the centre.
> Help then doesn’t logically belong as a tab in the top right.Perhaps there
> should be a clickable question mark on the far right of the tabs (there is
> blank space there now).
> I am not sure that Help is best on totally separate screens—I had thought
> it could be two other tabs on the same popup pane as the Quick Start, but I
> think that is what we’re doing with other CWRC interfaces so let’s try it
> for now.
>
>
>
>
>
>
>
> > On May 6, 2016, at 4:04 PM, Shawn Murphy <notifications@github.com>
> wrote:
> >
> > An advantage of having the "Quick Start" in its own little window is
> that one can refer to it while following along in the "Commands" tab so
> perhaps isn't well suited to display among the tabs.
> >
> > Likewise the "Huviz Documentation" (which is really great by the way!)
> would be cumbersome in a tab because it has a lot of internal structure
> (pages, links, etc) as well as including some large graphics:
> >
> > <
> https://camo.githubusercontent.com/0ba71e6d69b930eba21ffd00ef6e2d265a0c9018/687474703a2f2f626574612e637772632e63612f69736c616e646f72612f6f626a6563742f6377726325334134346131383962652d373730352d346139372d383134642d6266313839316661623337352f6461746173747265616d2f4f424a2f76696577
> >
> > Given these problems with the "Help" tab (neither sub section fitting
> well) I'd suggest the current situation is actually preferable.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub <
> https://github.com/cwrc/HuViz/issues/66#issuecomment-217544914>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/HuViz/issues/66#issuecomment-217598515>
>



-- 
Shawn Murphy
smurp@smurp.com
(780) 903-2428
http://www.smurp.com

**Comment by cmiya** [comment]
Yes, that's correct: the Help Tab would have two subsections: "Quick Start" and "Documentation" (with the current HuViz Documentation as the second tab). Something like this:

![image](https://cloud.githubusercontent.com/assets/13421476/15728695/6b518e34-281b-11e6-8a19-c6e042eb4f66.png)



Clicking on the "Quick Start" link would open it as its own window, as requested by you and Susan (I also think this is a good idea). Clicking on the "Documentation" would link to the [HuViz Documentation](http://cwrc.ca/HuViz_Documentation/).

I think this would also work well for the "About" section with the "Intro" and "Credits" as subsections, saving space at the top.

So again, the hierarchy for the main menu would be:

- About (main tab)
 - Intro (sub-tab)
 - Credits (sub-tab)

- Settings (main tab)
- Commands (main tab)
- Help (main tab)
 - Quick start (sub-tab)
 - Complete Manual (sub-tab)

**Comment by cmiya** [comment]
Here's a link to a GoogleDocs version of the [Credits page](https://docs.google.com/document/d/1uUExgbYxVGLwbHoZMqs9fAxeBDtpMCxUMrQuyV00qYs/edit?usp=sharing). The information has been updated (with input from the team members), so I believe it's good to go! @smurp feel edit your role description and add the years, if you like :)

@SusanBrown Is this ready to post on the HuViz credits tab?

**Comment by cmiya** [comment]
@smurp UPDATE: Here is a link to the final version of the [Credits Page](https://docs.google.com/document/d/1hpk8vSIDssubFAurL__ohkP4XpqNSGLawVLaMHpLstk/edit?usp=sharing). It's now ready for you to post on the site. The emails have been removed, as per @SusanBrown's request, to discourage spammers.
