### ISSUE TITLE
Make metadata about test datasets consistent

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#67]
Some cleanup before we test:
-- either remove the metadata about # of nodes available or make sure it is present to the same degree for all test datasets
-- comment out or remove the names of the unfeasible datasets that are greyed out so people aren't confused

**Comment by smurp** [comment]
Originally mis-read the second point... Now I've hidden the dangerous datasets and added a setting "Show dangerous datasets" which is off by default.  The dangerous ones are marked with a trailing (!)

4b782bf
