### ISSUE TITLE
TITLEs AKA Works are not appearing in the data extracts

### ISSUE THREAD

**Issue by smurp** [cwrc/HuViz#74]
Works used to appear in the extracts when they were being driven by the [regex rules](repo/blob/master/orlando2RDFregex4.txt) -- though the ontology connection was poor and they were displayed in HuViz as Thing rather than Work.  The new reliance on the [XPath rules](repo/blob/master/orlando2RDFxpath3.txt) has resulted in the disappearance of those Works from the extracts because there are no xpath rules which are referencing the TITLE tag in the XML.

The remedy is to extend the XPath rules to cover at least basic references to TITLE tags while using the latest ontology.

**Comment by SusanBrown** [comment]
I think this is redundant given new extraction processes.
