### ISSUE TITLE
Ontology viz missing?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#83]
@smurp is the ability to upload your own owl file gone for the moment? I can't find it.

**Comment by smurp** [comment]
The orlonto.html page does not offer that feature.  Is that where you weren't finding it?

What I'm working on is making it possible for the non-orlonto version of things to be able to do the things that orlonto does!  And what is that?  What it does is visualize ontologies.  I'm getting it to do that by providing an ontology (as orlonto does) which knows enough OWL to be able to contextualize the "data to visualize" (ie the RDF which is playing the role of `dataset`) so things like class-instance relations become edges in the graph (eg `SHAKWI rdf:type Person`)

**Comment by SusanBrown** [comment]
Yes, I thought we had been able to load an owl file into orlonto but perhaps it was a ttl file. At any rate, I think what you describe sounds great but it would be fine to keep the ontology visualization in a separate tab if that's easier. i.e. don't dive into this if it's a big time sink.

**Comment by cmiya** [comment]
Is anyone else having trouble loading the visualizations in the Orlonto version? I'm finding even the custom, pre-loaded sets are showing up blank. Here's the link I'm using: http://beta.huviz.dev.nooron.com/orlonto.html
