### ISSUE TITLE
Labels upon loading are undefined until moused over

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#85]
This is true in Orlonto but also to some extent in the main interface. You have to mouse over them before the label appears.

![image](https://cloud.githubusercontent.com/assets/545952/26038786/0a9bc4f2-3908-11e7-998e-eaacfdbe3ffa.png)

**Comment by cmiya** [comment]
Is this still an issue? I haven't experienced it myself, so I'm not sure
