### ISSUE TITLE
Provide a way to collapse the command panel down for small screens. 

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/HuViz#86]

**Comment by smurp** [comment]
Click tab names to switch between them. Clicking on the current tab `again` should collapse the pane leaving just the tab names.  Click a third time and the pane contents will again be revealed.

Or is the request for a way to shrink the command tab so its contents are smaller?

**Comment by SusanBrown** [comment]
No,this is great. Just didn't know about it or forgot if I did. @lemaka Please make screenshots both with and without the command panel expanded.
