### ISSUE TITLE
Start Point of Node List (On Shelf)

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#97]
Currently, the alphabetized node list (around the edge of the shelf) starts at the 3 o'clock point (as per mathematical standards). Could we allow users to determine the start point in the settings? Or perhaps allow for a toggle (12 o'clock vs. 3 o'clock or similar?)

So, let's add a setting
* [x] called `start point of shelf` 
* [x] reinstate flipping of labels, always at noon
* [ ] which has the options "12 o'clock", "3 o'clock", "6 o'clock" and "9 o'clock"

**Comment by wolfmaul** [comment]
I believe that the actual starting point is 6 o'clock (i.e. at bottom). The sort order means that entries started with numbers come before letters (i.e. "9" before "a")

**Comment by cmiya** [comment]
@wolfmaul @smurp It seems like the node display angle feature in the settings resolves this issue. Can we close this?
