### ISSUE TITLE
CWRC Ontology Issues

### ISSUE THREAD

**Issue by cmiya** [cwrc/HuViz#98]
CWRC Ontology Issues → Possible bug? How to ensure that the ontology is being respected? Need to check how CWRC ontology is working (note that no structure is being exhibited in the pickers)

**Comment by smurp** [comment]
https://github.com/smurp/huviz/commit/b2b2e7705a95501996b105522384acc3b70927a3

There is better support for the subClass relation as seen in the CWRC Ontology.  If the class picker isn't showing everything structured as it ought, please tell me which data file you're using with it when you see problems.

**Comment by cmiya** [comment]
Will this be resolved by CWRC Ontology Issue70: [Ensure Ontology and Dataset are consistent](https://github.com/cwrc/ontology/issues/70)? If so, should we close this issue and set it aside on the Huviz end?

**Comment by rwarren2** [comment]
It should be set aside on the Huviz, we're working on a script to automate the checking of data files.

**Comment by cmiya** [comment]
@rwarren2 Okay, thanks for the update!
